/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreasIndexRouteImport } from './routes/areas/index'
import { Route as AreasSlugRouteImport } from './routes/areas/$slug'
import { Route as HaulersIndexRouteImport } from './routes/haulers/index'
import { Route as HaulersSlugRouteImport } from './routes/haulers/$slug'
import { Route as WhatWeHaulIndexRouteImport } from './routes/what-we-haul/index'
import { Route as WhatWeHaulSlugRouteImport } from './routes/what-we-haul/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasIndexRoute = AreasIndexRouteImport.update({
  id: '/areas/',
  path: '/areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasSlugRoute = AreasSlugRouteImport.update({
  id: '/areas/$slug',
  path: '/areas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HaulersIndexRoute = HaulersIndexRouteImport.update({
  id: '/haulers/',
  path: '/haulers/',
  getParentRoute: () => rootRouteImport,
} as any)
const HaulersSlugRoute = HaulersSlugRouteImport.update({
  id: '/haulers/$slug',
  path: '/haulers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeHaulIndexRoute = WhatWeHaulIndexRouteImport.update({
  id: '/what-we-haul/',
  path: '/what-we-haul/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeHaulSlugRoute = WhatWeHaulSlugRouteImport.update({
  id: '/what-we-haul/$slug',
  path: '/what-we-haul/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/haulers/$slug': typeof HaulersSlugRoute
  '/what-we-haul/$slug': typeof WhatWeHaulSlugRoute
  '/areas/': typeof AreasIndexRoute
  '/haulers/': typeof HaulersIndexRoute
  '/what-we-haul/': typeof WhatWeHaulIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/haulers/$slug': typeof HaulersSlugRoute
  '/what-we-haul/$slug': typeof WhatWeHaulSlugRoute
  '/areas': typeof AreasIndexRoute
  '/haulers': typeof HaulersIndexRoute
  '/what-we-haul': typeof WhatWeHaulIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/haulers/$slug': typeof HaulersSlugRoute
  '/what-we-haul/$slug': typeof WhatWeHaulSlugRoute
  '/areas/': typeof AreasIndexRoute
  '/haulers/': typeof HaulersIndexRoute
  '/what-we-haul/': typeof WhatWeHaulIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/areas/$slug'
    | '/haulers/$slug'
    | '/what-we-haul/$slug'
    | '/areas/'
    | '/haulers/'
    | '/what-we-haul/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/areas/$slug'
    | '/haulers/$slug'
    | '/what-we-haul/$slug'
    | '/areas'
    | '/haulers'
    | '/what-we-haul'
  id:
    | '__root__'
    | '/'
    | '/areas/$slug'
    | '/haulers/$slug'
    | '/what-we-haul/$slug'
    | '/areas/'
    | '/haulers/'
    | '/what-we-haul/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreasSlugRoute: typeof AreasSlugRoute
  HaulersSlugRoute: typeof HaulersSlugRoute
  WhatWeHaulSlugRoute: typeof WhatWeHaulSlugRoute
  AreasIndexRoute: typeof AreasIndexRoute
  HaulersIndexRoute: typeof HaulersIndexRoute
  WhatWeHaulIndexRoute: typeof WhatWeHaulIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/': {
      id: '/areas/'
      path: '/areas'
      fullPath: '/areas/'
      preLoaderRoute: typeof AreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/$slug': {
      id: '/areas/$slug'
      path: '/areas/$slug'
      fullPath: '/areas/$slug'
      preLoaderRoute: typeof AreasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haulers/': {
      id: '/haulers/'
      path: '/haulers'
      fullPath: '/haulers/'
      preLoaderRoute: typeof HaulersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haulers/$slug': {
      id: '/haulers/$slug'
      path: '/haulers/$slug'
      fullPath: '/haulers/$slug'
      preLoaderRoute: typeof HaulersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-haul/': {
      id: '/what-we-haul/'
      path: '/what-we-haul'
      fullPath: '/what-we-haul/'
      preLoaderRoute: typeof WhatWeHaulIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-haul/$slug': {
      id: '/what-we-haul/$slug'
      path: '/what-we-haul/$slug'
      fullPath: '/what-we-haul/$slug'
      preLoaderRoute: typeof WhatWeHaulSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreasSlugRoute: AreasSlugRoute,
  HaulersSlugRoute: HaulersSlugRoute,
  WhatWeHaulSlugRoute: WhatWeHaulSlugRoute,
  AreasIndexRoute: AreasIndexRoute,
  HaulersIndexRoute: HaulersIndexRoute,
  WhatWeHaulIndexRoute: WhatWeHaulIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
