import { COMMUNITIES, type Community } from "@/lib/directory/communities";
import { FACTS, type ListingFacts } from "@/lib/directory/facts";
import { PROFILES } from "@/lib/directory/profiles";

export type Company = {
  slug: string;
  name: string;
  url: string | null;
  phone: string | null;
  email: string | null;
  address: string | null;
  hours: string | null;
  blurb: string;
  specialties: string[];
  needs: string[];
  /** "county" or community slugs this hauler says they cover. */
  coverage: "county" | string[];
  images: string[];
  featured?: boolean;
  /** Original factual notes from their site. */
  details?: string[];
  /** Pages on their own website. */
  links?: { label: string; href: string }[];
  facts?: ListingFacts;
};

const NORTH = [
  "del-mar",
  "solana-beach",
  "encinitas",
  "cardiff",
  "carlsbad",
  "oceanside",
  "vista",
  "san-marcos",
  "escondido",
  "poway",
  "rancho-santa-fe",
  "rancho-bernardo",
  "4s-ranch",
  "rancho-penasquitos",
  "carmel-valley",
  "mira-mesa",
  "scripps-ranch",
];

export const NEEDS = [
  { id: "same-day", label: "Same-day" },
  { id: "furniture", label: "Furniture" },
  { id: "appliances", label: "Appliances" },
  { id: "cleanout", label: "Cleanouts" },
  { id: "construction", label: "Construction debris" },
  { id: "commercial", label: "Commercial" },
  { id: "north-county", label: "North County" },
] as const;

export const COMPANIES: Company[] = [
  {
    slug: "freds-junk-removal",
    name: "Fred's Junk Removal",
    url: "https://www.fredsjunkremoval.com/",
    phone: "(619) 245-9957",
    email: "fred@fredsjunkremoval.com",
    address: null,
    hours: "Mon–Sat, 9:00 AM – 4:00 PM",
    blurb:
      "Local, veteran-owned hauler behind this directory. Posted household truck-load prices, same-day often available, and a photo text is the quote.",
    specialties: ["Furniture", "Appliances", "Garage cleanouts", "Same-day", "Posted pricing"],
    needs: ["same-day", "furniture", "appliances", "cleanout"],
    coverage: "county",
    images: [
      "/haulers/freds-junk-removal-photo-1.jpg",
      "/haulers/freds-junk-removal-photo-2.jpg",
      "/haulers/freds-junk-removal-photo-3.jpg",
      "/haulers/freds-junk-removal-photo-4.jpg",
    ],
    featured: true,
  },
  {
    slug: "jdog-junk-removal",
    name: "JDog Junk Removal & Hauling",
    url: "https://www.jdogjunkremoval.com/locations/california/san-diego-junk-removal/",
    phone: "(844) 438-5364 · (760) 291-8917",
    email: null,
    address: null,
    hours: null,
    blurb:
      "Veteran-owned, military-family franchise for homes and businesses. The San Diego location is run by brothers Ryan and Seamus Fitzpatrick and covers junk removal, light demolition, dumpster rentals, and cleanouts.",
    specialties: ["Veteran-owned", "Dumpster rental", "Light demolition", "Cleanouts", "Commercial"],
    needs: ["furniture", "appliances", "cleanout", "construction", "commercial", "north-county"],
    coverage: [
      "la-jolla",
      "pacific-beach",
      "chula-vista",
      "el-cajon",
      "la-mesa",
      "escondido",
      "oceanside",
      "carlsbad",
      "encinitas",
      "poway",
      "rancho-santa-fe",
      "solana-beach",
      "vista",
    ],
    images: [
      "/haulers/jdog-trucks.jpeg",
      "/haulers/jdog-trailer.jpeg",
      "/haulers/jdog-logo.jpeg",
    ],
  },
  {
    slug: "junk-be-gone",
    name: "Junk Be Gone Inc",
    url: "https://junkbegoneinc.com/",
    phone: "(657) 254-3058",
    email: "info@junkbegoneinc.com",
    address: null,
    hours: null,
    blurb:
      "Full-service junk removal and demolition company based in San Diego. Homes and businesses, light demolition, cleanouts, moving help, and hot tub, appliance, and furniture hauling. They say they recycle up to 80% of each load.",
    specialties: ["Light demolition", "Cleanouts", "Moving help", "Hot tubs", "Recycles up to 80%"],
    needs: ["furniture", "appliances", "construction", "commercial", "cleanout"],
    coverage: "county",
    images: ["/haulers/junk-be-gone-logo.jpeg"],
  },
  {
    slug: "junk-punch",
    name: "Junk Punch Junk Removal",
    url: "https://junk-punch.com/",
    phone: "(619) 219-1503",
    email: "sdjunkpunch@gmail.com",
    address: "San Diego, CA 92102",
    hours: "Mon–Sat 6 AM – 8 PM, Sun 6 AM – 9 PM",
    blurb:
      "Family-owned hauler started in September 2021 by Hector and Lucy Rodriguez. They serve Chula Vista, San Diego, and the rest of the county, with same-day or next-day pickup including weekends.",
    specialties: ["Family-owned", "Same-day", "Furniture", "Cleanouts", "Recycling"],
    needs: ["same-day", "furniture", "appliances", "cleanout", "commercial"],
    coverage: "county",
    images: [
      "/haulers/junk-punch-photo-1.jpg",
      "/haulers/junk-punch-load.jpeg",
      "/haulers/junk-punch-crew.jpeg",
    ],
  },
  {
    slug: "the-wreckin-haul",
    name: "The Wreckin' Haul",
    url: "https://www.thewreckinhaul.com/",
    phone: "(760) 421-5331",
    email: "info@thewreckinhaul.com",
    address: "Valley Center, CA",
    hours: null,
    blurb:
      "Veteran-owned, family-run junk removal, dumpster rental, and property cleanouts based in Valley Center. Owner Sean Guerra covers North County San Diego, with same-day or next-day service.",
    specialties: ["Veteran-owned", "Dumpster rental", "Estate cleanouts", "Construction debris", "Same-day"],
    needs: ["same-day", "furniture", "appliances", "cleanout", "construction", "commercial", "north-county"],
    coverage: [...NORTH, "ramona"],
    images: [
      "/haulers/the-wreckin-haul-photo-2.webp",
      "/haulers/the-wreckin-haul-photo-3.webp",
      "/haulers/the-wreckin-haul-photo-4.webp",
      "/haulers/the-wreckin-haul-photo-1.jpg",
    ],
  },
  {
    slug: "junk-guys-san-diego",
    name: "Junk Guys San Diego",
    url: "https://www.junkguyssandiego.com/",
    phone: "(760) 415-9811",
    email: null,
    address: null,
    hours: null,
    blurb:
      "Greater San Diego junk and trash pickup. They name North County and South Bay cities, and they take furniture, appliances, electronics, and garage, estate, hoarding, eviction, and foreclosure cleanouts.",
    specialties: ["Cleanouts", "Furniture", "Appliances", "North County"],
    needs: ["furniture", "appliances", "cleanout", "north-county"],
    coverage: "county",
    images: [
      "/haulers/junk-guys-flyer.jpg",
      "/haulers/junk-guys-logo.jpeg",
    ],
  },
  {
    slug: "dmd-junk-removal",
    name: "DMD Junk Removal",
    url: "https://www.dmdjunkremoval.com/",
    phone: "(951) 401-5933",
    email: "info@dmdjunkremoval.com",
    address: "San Marcos, CA",
    hours: "7 days, 7 AM – 7 PM",
    blurb:
      "Owner-operated North County hauler in San Marcos. The site says you reach David at (951) 401-5933. Single items from $125 and full trailers $700–$750, plus 12 ft and 14 ft trailer rentals.",
    specialties: ["Dump trailer rental", "Junk removal", "North County"],
    needs: ["north-county", "construction"],
    coverage: NORTH,
    images: [
      "/haulers/dmd-junk-removal-photo-3.jpg",
      "/haulers/dmd-junk-removal-photo-4.jpg",
      "/haulers/dmd-junk-removal-photo-1.jpg",
      "/haulers/dmd-crew.jpeg",
    ],
  },
  {
    slug: "the-hauler",
    name: "The Hauler Junk Removal",
    url: "https://www.thehaulerjunkremoval.com/",
    phone: "(760) 331-3289",
    email: "thehaulerjunkremoval@gmail.com",
    address: "Vista, CA 92081",
    hours: null,
    blurb:
      "Family-owned North County hauler based in Vista. Bulk trash, garage and estate cleanouts, appliances, e-waste, and construction cleanup, with same-day or next-day service listed.",
    specialties: ["Family-owned", "North County", "Cleanouts", "Appliances", "Same-day"],
    needs: ["same-day", "furniture", "appliances", "cleanout", "construction", "north-county"],
    coverage: NORTH,
    images: [
      "/haulers/the-hauler-extra-4.jpg",
      "/haulers/the-hauler-extra-3.jpg",
      "/haulers/the-hauler-truck.jpg",
      "/haulers/the-hauler-extra-2.jpg",
    ],
  },
  {
    slug: "ace-hauling",
    name: "Ace Hauling",
    url: "https://www.acehauling.com/",
    phone: "(760) 332-3366 · (800) 720-4285",
    email: "infoacehauling@gmail.com",
    address: "Encinitas, CA",
    hours: null,
    blurb:
      "Family-owned junk removal and demolition company run by Nick Marchand, in business more than 20 years. Same-day or next-day estimates across San Diego County. They will not take hazardous items, liquids, or asbestos.",
    specialties: ["Family-owned", "Demolition", "Same-day", "20+ years", "Licensed"],
    needs: ["construction", "commercial", "cleanout"],
    coverage: "county",
    images: [
      "/haulers/ace-hauling-photo-1.jpg",
      "/haulers/ace-hauling-photo-2.jpg",
      "/haulers/ace-hauling-photo-3.jpg",
      "/haulers/ace-hauling-photo-4.jpg",
    ],
  },
  {
    slug: "junk-fairy",
    name: "Junk Fairy",
    url: "https://www.junkfairy.com/",
    phone: "(858) 361-7941",
    email: "info@junkfairy.com",
    address: "10884 Sabre Hill Dr, San Diego, CA 92128",
    hours: null,
    blurb:
      "Family-owned San Diego crew, known for the pink truck. Full-service pickups start at $145, with same-day or next-day service and posted load prices.",
    specialties: ["Family-owned", "Posted pricing", "Furniture", "Appliances", "Same-day"],
    needs: ["same-day", "furniture", "appliances", "cleanout", "commercial"],
    coverage: "county",
    images: [
      "/haulers/junk-fairy-photo-4.webp",
      "/haulers/junk-fairy-photo-1.webp",
      "/haulers/junk-fairy-photo-2.webp",
      "/haulers/junk-fairy-photo-3.webp",
    ],
  },
  {
    slug: "haul-away-any-day",
    name: "Haul Away Any Day",
    url: "https://haulawayanyday.com/",
    phone: "(619) 277-7241",
    email: "info@haulawayanyday.com",
    address: null,
    hours: "7:00 AM – 7:00 PM",
    blurb:
      "Family-owned San Diego hauler run by Francisco and Yadira. Furniture, appliances, yard waste, and construction debris, with same-day or next-day service and upfront pricing.",
    specialties: ["Family-owned", "Same-day", "Furniture", "Appliances", "Construction debris"],
    needs: ["same-day", "furniture", "appliances", "cleanout"],
    coverage: "county",
    images: [
      "/haulers/haul-away-any-day-photo-1.jpg",
      "/haulers/haul-away-any-day-photo-2.jpg",
      "/haulers/haul-away-any-day-photo-4.jpg",
    ],
  },
  {
    slug: "junkmates",
    name: "JunkMates",
    url: "https://www.junkmatessd.com/",
    phone: "(858) 740-4750",
    email: "contact@junkmatessd.com",
    address: "1053 Regal Rd, Encinitas, CA 92024",
    hours: "Mon–Sat 7 AM – 7 PM, Sun 8 AM – 4 PM",
    blurb:
      "Encinitas hauler for homes and businesses. Same-day pickup, free on-site estimates, and donated or recycled items. Their FAQ says they cover from Oceanside down to Petco Park.",
    specialties: ["Dumpster rental", "Hot tubs", "Commercial", "Countywide"],
    needs: ["furniture", "appliances", "commercial", "cleanout", "north-county"],
    coverage: "county",
    images: [
      "/haulers/junkmates-photo-1.jpg",
      "/haulers/junkmates-photo-2.jpg",
      "/haulers/junkmates-photo-4.webp",
      "/haulers/junkmates-photo-3.webp",
    ],
  },
  {
    slug: "the-hauling-crew",
    name: "The Hauling Crew",
    url: "https://www.thehaulingcrewsd.com/",
    phone: "(619) 490-0223",
    email: "sdhaulingcrew@gmail.com",
    address: "P.O. Box 16364, San Diego, CA 92176",
    hours: "7:00 AM – 5:00 PM",
    blurb:
      "Family-owned San Diego crew for appliances, furniture, electronics, construction hauling, and cleanouts. They offer free on-site estimates and a curbside discount.",
    specialties: ["Family-owned", "Appliances", "Construction", "Cleanouts", "Free estimates"],
    needs: ["furniture", "appliances", "construction", "commercial", "cleanout"],
    coverage: "county",
    images: [
      "/haulers/the-hauling-crew-photo-1.jpg",
      "/haulers/the-hauling-crew-photo-2.jpg",
      "/haulers/the-hauling-crew-photo-3.jpg",
      "/haulers/the-hauling-crew-photo-4.jpg",
    ],
  },
  {
    slug: "jb-solutions",
    name: "J&B Solutions",
    url: "https://jandbsolutionsca.com/",
    phone: "(619) 357-9587",
    email: "byron@jandbsolutionsca.com",
    address: "Lakeside, CA",
    hours: null,
    blurb:
      "Licensed hauler out of Lakeside that takes residential and commercial junk across San Diego County and also rents dumpsters.",
    specialties: ["Dumpster rental", "Demolition", "Lakeside"],
    needs: ["construction", "commercial", "cleanout"],
    coverage: "county",
    images: [
      "/haulers/jb-solutions-trailer.jpg",
      "/haulers/jb-solutions-pile.jpg",
      "/haulers/jb-solutions-logo.jpg",
    ],
  },
  {
    slug: "ruiz-junk-removal",
    name: "Ruiz Junk Removal and Hauling",
    url: "https://ruizjunkremovalandhauling.com/",
    phone: "(619) 253-3200",
    email: "Ruizjunkremoval.hauling@gmail.com",
    address: null,
    hours: null,
    blurb:
      "Cole’s San Diego crew for junk, trash, and demo debris. Small pickups start at $125. Trash loads are listed at $250–$500, and full demo loads at $550–$650. Send photos for an estimate.",
    specialties: ["Cleanouts", "Demo debris", "Photo estimates"],
    needs: ["cleanout", "construction"],
    coverage: "county",
    images: [
      "/haulers/ruiz-junk-removal-photo-2.jpg",
      "/haulers/ruiz-junk-removal-photo-3.jpg",
      "/haulers/ruiz-junk-removal-photo-4.jpg",
    ],
  },
  {
    slug: "sa-junk-haul",
    name: "SA Junk Haul",
    url: "https://sajunkhaul.com/service-area/san-diego-ca/",
    phone: "(760) 708-1965",
    email: "Estimates@SAjunkhaul.com",
    address: "San Marcos, CA",
    hours: null,
    blurb:
      "North County hauler based in San Marcos. Homes and businesses, furniture, appliances, yard waste, and construction debris, with same-day service listed.",
    specialties: ["Same-day", "North County", "Furniture", "Appliances", "Cleanouts"],
    needs: ["furniture", "appliances", "cleanout", "commercial"],
    coverage: "county",
    images: [
      "/haulers/sa-junk-haul-photo-1.jpg",
      "/haulers/sa-junk-haul-photo-2.jpg",
      "/haulers/sa-junk-haul-photo-3.jpg",
      "/haulers/sa-junk-haul-photo-4.jpg",
    ],
  },
  {
    slug: "severin-hauling",
    name: "Severin Hauling",
    url: "https://www.severinhauling.com/",
    phone: "(619) 750-0114",
    email: "severinhauling@gmail.com",
    address: "8900 Grossmont Blvd, Suite 1, La Mesa, CA 91941",
    hours: "Open 24 hours",
    blurb:
      "Locally owned La Mesa hauler with posted volume prices from $69 for a small item to $495 for a full load. Same-day across San Diego County when you call before 2 PM. Labor, dump fees, and recycling are included.",
    specialties: ["Posted item prices", "Same-day", "La Mesa"],
    needs: ["same-day", "furniture", "cleanout"],
    coverage: "county",
    images: [
      "/haulers/severin-hauling-photo-1.jpg",
      "/haulers/severin-hauling-photo-2.jpg",
      "/haulers/severin-hauling-photo-3.jpg",
      "/haulers/severin-hauling-photo-4.jpg",
    ],
  },
  {
    slug: "haul-out",
    name: "Haul Out Junk Removal",
    url: "https://www.hauloutjunkremoval.com/",
    phone: "(760) 685-9332",
    email: "hauloutjunkremovalsd@gmail.com",
    address: null,
    hours: null,
    blurb:
      "Veteran- and family-owned San Diego hauler run by Jerry and Michele Scott. Text a photo for a quote. Curbside single items are $79–$99, and larger loads are posted up to $599. They do not take chemicals, propane, or paint.",
    specialties: ["Veteran-owned", "Family-owned", "Posted pricing", "Residential", "Commercial"],
    needs: ["commercial", "cleanout", "furniture"],
    coverage: "county",
    images: [
      "/haulers/haul-out-photo-1.jpg",
      "/haulers/haul-out-photo-3.jpg",
      "/haulers/haul-out-photo-2.jpg",
    ],
  },
  {
    slug: "demo-diego",
    name: "Demo Diego",
    url: "https://www.demodiego.com/junk-removal",
    phone: "(760) 860-8080",
    email: "demodiego619@gmail.com",
    address: null,
    hours: null,
    blurb:
      "Family-owned demolition and junk removal company with 20-plus years in San Diego County. Same-day household hauling plus pools, concrete, kitchens, and other tear-outs. The quote is flat-rate before work starts.",
    specialties: ["Demolition", "Same-day", "Estate cleanouts", "Posted pricing", "Family-owned"],
    needs: ["same-day", "furniture", "appliances", "cleanout", "construction", "commercial"],
    coverage: "county",
    images: [
      "/haulers/demo-diego-photo-3.jpg",
      "/haulers/demo-diego-photo-1.jpg",
      "/haulers/demo-diego-photo-2.jpg",
      "/haulers/demo-diego-photo-4.jpg",
    ],
  },
  {
    slug: "the-junk-transporter",
    name: "The Junk Transporter",
    url: "https://thejunktransporter.com/",
    phone: "(760) 522-3215",
    email: "TheJunkTransporter@gmail.com",
    address: null,
    hours: "8:00 AM – 8:00 PM, 7 days",
    blurb:
      "Family-owned county hauler. Minimum loads from $90, a half dump truck $350, and a full dump truck $550. Furniture, appliances, spas, yard waste, and cleanouts.",
    specialties: ["Same-day", "Hot tubs", "Countywide"],
    needs: ["same-day", "cleanout", "furniture"],
    coverage: "county",
    images: ["/haulers/the-junk-transporter-photo-1.jpg"],
  },
  {
    slug: "junkmd",
    name: "JunkMD",
    url: "https://junkmd.com/",
    phone: "(858) 869-9448",
    email: "dave@junkmd.com",
    address: "4901 Morena Blvd #105, San Diego, CA 92117",
    hours: "Mon–Sat",
    blurb:
      "Family-owned San Diego hauler since 2012. Flat-rate truck pricing from a $119 minimum to $899 for a full truck, same-day or next-day, with donation and recycling first.",
    specialties: ["Family-owned", "Flat-rate", "Same-day", "Since 2012"],
    needs: ["same-day", "cleanout", "furniture"],
    coverage: "county",
    images: [
      "/haulers/junkmd-photo-3.jpg",
      "/haulers/junkmd-photo-1.jpg",
      "/haulers/junkmd-photo-4.jpg",
      "/haulers/junkmd-photo-5.jpg",
    ],
  },
  {
    slug: "priority-hauling",
    name: "Priority Hauling",
    url: "https://www.priorityhaulingsd.com/",
    phone: "(619) 363-2581",
    email: null,
    address: null,
    hours: "7:00 AM – 5:00 PM",
    blurb:
      "San Diego County hauler owned by Austin J. Same-day or next-day pickup for furniture, appliances, mattresses, yard waste, construction debris, and cleanouts. Free quotes by text. Senior and veteran discounts are listed.",
    specialties: ["Same-day", "Cleanouts", "Furniture", "Construction debris", "Licensed"],
    needs: ["same-day", "furniture", "appliances", "cleanout", "construction", "commercial"],
    coverage: "county",
    images: [
      "/haulers/priority-hauling-extra-5.jpg",
      "/haulers/priority-hauling-photo-3.jpg",
      "/haulers/priority-hauling-extra-2.jpg",
    ],
  },
  {
    slug: "pick-and-dump",
    name: "Pick and Dump",
    url: "https://www.pickanddump.com/",
    phone: "(619) 257-4827 · (619) 552-2885",
    email: "sales@pickanddump.com",
    address: "333 Palm Ave, Chula Vista, CA 91911",
    hours: null,
    blurb:
      "Chula Vista junk removal for a single item or a full property cleanout. Same-day or next-day. The quote includes labor, travel, and disposal. They name National City, Bonita, Imperial Beach, Spring Valley, La Mesa, and Jamul.",
    specialties: ["Chula Vista", "Same-day", "Cleanouts", "Upfront pricing"],
    needs: ["same-day", "furniture", "appliances", "cleanout", "commercial"],
    coverage: "county",
    images: [
      "/haulers/pick-and-dump-photo-1.jpg",
      "/haulers/pick-and-dump-photo-2.jpg",
      "/haulers/pick-and-dump-photo-3.jpg",
      "/haulers/pick-and-dump-photo-4.jpg",
    ],
  },
  {
    slug: "crisan-junk-removal",
    name: "Crisan Junk Removal",
    url: "https://crisanjunkremoval.com/",
    phone: "(619) 500-9920",
    email: "contact@crisantransport.com",
    address: null,
    hours: null,
    blurb:
      "Family-owned San Diego County hauler founded in 2021 by Jorge I. Pimentel. Posted truck prices from a $177 minimum to $827 for a full load. Book online and they take $20 off. Licensed and insured.",
    specialties: ["Family-owned", "Posted pricing", "Light demolition", "Cleanouts"],
    needs: ["furniture", "appliances", "cleanout", "construction", "commercial"],
    coverage: "county",
    images: [
      "/haulers/crisan-junk-removal-photo-1.webp",
      "/haulers/crisan-junk-removal-photo-4.webp",
    ],
  },
  {
    slug: "jc-junk-removal",
    name: "JC Junk Removal",
    url: "https://jcjunkremovalservices.com/",
    phone: "(619) 805-5104",
    email: "Jcjunkremovalservices24@gmail.com",
    address: "2917 Morningside St, San Diego, CA 92139",
    hours: null,
    blurb:
      "Family-owned, licensed San Diego hauler serving the county. Furniture, appliances, commercial cleanups, and general junk. Quotes can start from a photo.",
    specialties: ["Local hauling"],
    needs: ["cleanout"],
    coverage: "county",
    images: [
      "/haulers/jc-junk-removal-photo-2.jpg",
      "/haulers/jc-junk-removal-photo-4.jpg",
      "/haulers/jc-junk-removal-photo-3.jpg",
    ],
  },
  {
    slug: "junk-junkys",
    name: "Junk Junkys",
    url: "https://junkjunkys.com/",
    phone: "(858) 399-1540",
    email: "Junkjunkysmarketing@gmail.com",
    address: "10606 Camino Ruiz, Ste 8-218, San Diego, CA 92126",
    hours: "Mon–Sun, 9 AM – 6 PM",
    blurb:
      "Founded by Umaid Shah. Furniture, appliances, hot tubs, construction debris, and cleanouts across San Diego County, with free quotes and recycling.",
    specialties: ["Eco-friendly", "Local hauling"],
    needs: ["cleanout", "furniture"],
    coverage: "county",
    images: ["/haulers/junk-junkys-photo-3.jpg"],
  },
  {
    slug: "bay-junk",
    name: "Bay Junk",
    url: "https://www.bayjunk.com/locations/California/junk-removal-san-diego",
    phone: "(619) 488-6969",
    email: "info@bayjunk.com",
    address: "1812 Chalcedony St, San Diego, CA 92109",
    hours: "Mon–Sat 7:30 AM – 7:30 PM, Sun 8 AM – 5 PM",
    blurb:
      "San Diego junk removal with same-day pickup. Yelp lists Edgardo B. as the owner. On-site quotes include labor, transport, and disposal. The site advertises $35 off when you book. They recycle and donate, and they will not take paint, chemicals, or other hazardous items.",
    specialties: ["San Diego page", "Furniture", "Cleanouts"],
    needs: ["furniture", "cleanout", "commercial"],
    coverage: [
      "solana-beach",
      "encinitas",
      "cardiff",
      "carmel-valley",
      "poway",
      "la-jolla",
      "la-mesa",
      "el-cajon",
      "del-mar",
      "carlsbad",
      "rancho-bernardo",
    ],
    images: [
      "/haulers/bay-junk-photo-3.jpg",
      "/haulers/bay-junk-photo-1.jpg",
    ],
  },
  {
    slug: "junk-away-san-diego",
    name: "Junk Away San Diego",
    url: "https://junkawaysandiego.com/",
    phone: "(858) 321-5555",
    email: "support@junkawaysandiego.com",
    address: null,
    hours: null,
    blurb:
      "Family-owned hauler for homes and businesses. Same-day and next-day pickup, upfront quotes, and donation or recycling. Addresses listed in Carlsbad and Solana Beach.",
    specialties: ["Same-day", "Cleanouts", "Upfront pricing"],
    needs: ["same-day", "cleanout", "commercial"],
    coverage: "county",
    images: [
      "/haulers/junk-away-san-diego-photo-2.jpg",
      "/haulers/junk-away-san-diego-photo-4.jpg",
      "/haulers/junk-away-san-diego-photo-3.jpg",
    ],
  },
  {
    slug: "fast-pickup-junk",
    name: "Fast Pickup Junk",
    url: "https://fastpickupjunksd.com/",
    phone: null,
    email: null,
    address: null,
    hours: null,
    blurb:
      "Locally owned San Diego metro hauler. Furniture, appliances, cleanouts, and shed or hot tub demolition. They advertise $20 off and price by how full the truck is. Quotes go through the site.",
    specialties: ["Residential", "Commercial", "Metro San Diego"],
    needs: ["commercial", "cleanout", "north-county"],
    coverage: "county",
    images: [
      "/haulers/fast-pickup-junk-loads.jpg",
      "/haulers/fast-pickup-junk-job.jpg",
      "/haulers/fast-pickup-junk-logo.jpg",
    ],
  },
  {
    slug: "flash-junk-removal",
    name: "Flash Junk Removal",
    url: "https://www.flashjunkremoval.com/",
    phone: "(760) 639-8778",
    email: "Flashjunkremoval@gmail.com",
    address: null,
    hours: "Mon–Sun, 7 AM – 7 PM",
    blurb:
      "Countywide hauler advertising same-day or next-day truck loads, plus appliances, mattresses, furniture, hoarding cleanouts, and construction debris.",
    specialties: ["Same-day", "Hoarding cleanouts", "Construction debris", "Dumpsters"],
    needs: ["same-day", "furniture", "appliances", "cleanout", "construction"],
    coverage: "county",
    images: [
      "/haulers/flash-junk-removal-photo-1.jpg",
      "/haulers/flash-junk-removal-photo-2.jpg",
      "/haulers/flash-junk-removal-photo-3.jpg",
    ],
  },
  {
    slug: "clear-junk-removal",
    name: "Clear Junk Removal",
    url: "https://www.clearjunkremoval.com/",
    phone: "(760) 405-4347",
    email: "pmarchand06@gmail.com",
    address: "11846 Scripps Creek Drive, San Diego, CA 92131",
    hours: null,
    blurb:
      "North County crew based in Scripps Ranch. They list same-day work plus furniture, appliances, construction debris, and foreclosure cleanouts.",
    specialties: ["Same-day", "North County", "Foreclosure cleanouts"],
    needs: ["same-day", "furniture", "appliances", "construction", "north-county", "cleanout"],
    coverage: [
      "del-mar",
      "poway",
      "oceanside",
      "carlsbad",
      "vista",
      "san-marcos",
      "scripps-ranch",
      "rancho-bernardo",
      "encinitas",
      "rancho-penasquitos",
      "mira-mesa",
      "escondido",
    ],
    images: [
      "/haulers/clear-junk-removal-photo-1.jpg",
      "/haulers/clear-junk-removal-photo-4.jpg",
    ],
  },
  {
    slug: "junk-rushed",
    name: "Junk Rushed",
    url: "https://junkrushed.com/",
    phone: "(619) 248-9003",
    email: "ray@junkrushsd.com",
    address: null,
    hours: "Mon–Fri, 8 AM – 8 PM",
    blurb:
      "Locally owned county hauler for homes, businesses, and job sites. Same-day is listed, along with yard waste, appliances, and furniture.",
    specialties: ["Same-day", "Yard waste", "Veteran-owned"],
    needs: ["same-day", "furniture", "appliances", "commercial"],
    coverage: "county",
    images: [
      "/haulers/junk-rushed-photo-1.jpg",
      "/haulers/junk-rushed-photo-2.jpg",
      "/haulers/junk-rushed-photo-3.jpg",
      "/haulers/junk-rushed-photo-4.jpg",
    ],
  },
  {
    slug: "pacific-rim-junk",
    name: "Pacific Rim Junk",
    url: "https://pacificrimjunk.com/",
    phone: "(760) 613-1111",
    email: "info@pacificrimjunk.com",
    address: "Encinitas, CA",
    hours: null,
    blurb:
      "Family-owned Encinitas company that says it covers San Diego County neighborhoods, including same-day furniture, e-waste, yard waste, and construction debris.",
    specialties: ["Same-day", "E-waste", "Construction debris", "Encinitas"],
    needs: ["same-day", "furniture", "appliances", "construction", "north-county"],
    coverage: "county",
    images: [
      "/haulers/pacific-rim-junk-photo-1.jpg",
      "/haulers/pacific-rim-junk-photo-4.jpg",
      "/haulers/pacific-rim-junk-photo-3.jpg",
    ],
  },
  {
    slug: "strong-hauling",
    name: "Strong Hauling",
    url: "https://www.stronghauling.com/",
    phone: "(858) 866-9345",
    email: null,
    address: null,
    hours: "Open daily, 7 AM – 7 PM",
    blurb:
      "Family-owned county hauler open daily. The site lists furniture, hoarder cleanouts, hot tubs, appliances, and yard debris, with same-day or next-day.",
    specialties: ["Hoarder cleanouts", "Hot tubs", "Daily hours"],
    needs: ["same-day", "furniture", "appliances", "cleanout"],
    coverage: "county",
    images: [
      "/haulers/strong-hauling-photo-1.jpg",
      "/haulers/strong-hauling-photo-2.jpg",
      "/haulers/strong-hauling-photo-4.webp",
      "/haulers/strong-hauling-photo-3.webp",
    ],
  },
  {
    slug: "the-junkiez",
    name: "The Junkiez",
    url: "https://sd.thejunkiez.com/",
    phone: "(619) 759-7005",
    email: null,
    address: null,
    hours: null,
    blurb:
      "San Diego crew with full-service pickup starting at $99 and same-day service seven days a week. They also list some Orange County and Los Angeles cities.",
    specialties: ["Same-day", "Furniture", "Exercise equipment"],
    needs: ["same-day", "furniture", "appliances", "cleanout"],
    coverage: "county",
    images: [
      "/haulers/the-junkiez-photo-2.jpg",
      "/haulers/the-junkiez-photo-1.jpg",
      "/haulers/the-junkiez-photo-3.jpg",
      "/haulers/the-junkiez-photo-4.jpg",
    ],
  },
  {
    slug: "monarch-junk-removal",
    name: "Monarch Junk Removal",
    url: "https://monarchjunkremoval.com/",
    phone: "(844) 619-5865 · (619) 806-2978",
    email: "info@monarchjunkremoval.com",
    address: "4142 Adams Ave Ste 103 Box 430, San Diego, CA 92116",
    hours: null,
    blurb:
      "Veteran-owned, locally owned county hauler. Truck prices run from about $125 for a minimum load to $650–$800 for a full truck. Furniture, appliances, yard waste, office junk, and hot tubs.",
    specialties: ["Veteran-owned", "Office junk", "Hot tubs", "Same-day"],
    needs: ["same-day", "furniture", "appliances", "commercial", "cleanout"],
    coverage: "county",
    images: [
      "/haulers/monarch-junk-removal-photo-3.jpg",
      "/haulers/monarch-junk-removal-photo-1.jpg",
      "/haulers/monarch-junk-removal-photo-4.jpg",
    ],
  },
  {
    slug: "fetch-junk",
    name: "FETCH Junk Removal",
    url: "https://www.fetchjunk.com/",
    phone: "(619) 333-8447",
    email: "fetchjunkremoval@gmail.com",
    address: "9131 Fletcher Pkwy, Suite 122b, La Mesa, CA 91942",
    hours: "6:30 AM – 9:00 PM, 7 days",
    blurb:
      "Family-owned La Mesa company run by Daniel V. Prices start at $89. A half load is $349 and a full load is $649. Hours are 6:30 AM to 9:00 PM, seven days, across San Diego County.",
    specialties: ["Photo quotes", "Construction debris", "La Mesa", "Same-day"],
    needs: ["same-day", "construction", "furniture", "appliances", "cleanout"],
    coverage: "county",
    images: [
      "/haulers/fetch-junk-photo-2.jpg",
      "/haulers/fetch-junk-photo-1.jpg",
      "/haulers/fetch-junk-photo-3.jpg",
    ],
  },
  {
    slug: "you-call-it-we-haul-it",
    name: "You Call It We Haul It",
    url: "https://www.youcallitwehaulitca.com/",
    phone: "(858) 215-5815",
    email: "youcallitwehaulitfast@gmail.com",
    address: "488 Emerson St., Chula Vista, CA 91911",
    hours: "Mon–Sun, 6:00 AM – 8:00 PM",
    blurb:
      "Family- and woman-owned Chula Vista hauler. They publish a long city list from the South Bay through North County and say same-day or next-day is available.",
    specialties: ["Chula Vista", "Appliances", "Commercial", "Same-day"],
    needs: ["same-day", "appliances", "furniture", "commercial", "construction"],
    coverage: [
      "alpine",
      "bonita",
      "cardiff",
      "carlsbad",
      "chula-vista",
      "coronado",
      "del-mar",
      "el-cajon",
      "encinitas",
      "escondido",
      "imperial-beach",
      "jamul",
      "la-jolla",
      "la-mesa",
      "lakeside",
      "lemon-grove",
      "poway",
      "ramona",
      "rancho-san-diego",
      "rancho-santa-fe",
      "san-marcos",
      "san-ysidro",
      "santee",
      "solana-beach",
      "spring-valley",
      "vista",
    ],
    images: [
      "/haulers/you-call-it-we-haul-it-photo-3.jpg",
      "/haulers/you-call-it-we-haul-it-photo-4.jpg",
      "/haulers/you-call-it-we-haul-it-photo-1.jpg",
    ],
  },
  {
    slug: "junk-haul-team",
    name: "Junk Haul Team",
    url: "https://junkhaulteam.com/",
    phone: "(619) 851-6426",
    email: null,
    address: "San Diego, CA 92102",
    hours: null,
    blurb:
      "Veteran-owned, licensed San Diego crew covering the county with same-day service. A $99 special is advertised. Furniture, appliances, construction cleanup, and storage units.",
    specialties: ["Veteran-owned", "Same-day", "Storage units"],
    needs: ["same-day", "furniture", "appliances", "construction", "cleanout"],
    coverage: "county",
    images: ["/haulers/junk-haul-team-photo-1.jpg"],
  },
  {
    slug: "gti-hauling",
    name: "Gti Hauling",
    url: null,
    phone: "(619) 560-6753",
    email: null,
    address: "1455 Frazee Rd Ste 500, San Diego, CA 92108",
    hours: "Daily, 6:00 AM – 9:00 PM",
    blurb:
      "Mission Valley hauler on Yelp and BBB at this phone. Owner George Loyd. Junk, appliances, furniture, mattresses, electronics, and property cleanouts. A Nextdoor page also lists 14260 Garden Road, Poway.",
    specialties: ["Appliances", "Furniture", "Property cleanouts", "Yard waste"],
    needs: ["furniture", "appliances", "cleanout"],
    coverage: ["mission-valley"],
    images: [],
  },
  {
    slug: "gabriels-junk-removal",
    name: "Gabriel's Junk Removal",
    url: "https://gabrielsjunkremoval.net/",
    phone: "(619) 957-4592",
    email: null,
    address: "1903 Isla Del Carmen Wy, San Diego, CA 92173",
    hours: null,
    blurb:
      "Locally owned, family-run hauler. The site serves San Diego, Chula Vista, Del Mar, and surrounding areas, with free on-site estimates. A flyer at this phone also advertises dumpster rental and says to text a photo of the junk.",
    specialties: ["Family-owned", "Locally owned", "Dumpster rental", "Free estimates"],
    needs: ["cleanout"],
    coverage: ["chula-vista", "del-mar"],
    images: [
      "/haulers/gabriels-junk-removal-photo-2.jpg",
      "/haulers/gabriels-junk-removal-photo-1.webp",
      "/haulers/gabriels-junk-removal-photo-3.jpg",
      "/haulers/gabriels-junk-removal-photo-4.jpg",
    ],
  },
  {
    slug: "nicos-hauling",
    name: "Nico's Hauling",
    url: null,
    phone: "(619) 862-9916",
    email: null,
    address: "4220 51st St #9, San Diego, CA 92115",
    hours: "Mon–Fri 7:00 AM – 7:00 PM; Sat–Sun 7:00 AM – 6:00 PM",
    blurb:
      "San Diego Yelp listing for this phone, owner Edgar G., in the Rolando / 92115 area. Junk, appliances, furniture, yard waste, construction debris, and demolition. A different Nico’s Hauling in Pacifica uses another phone, so that site is not linked here.",
    specialties: ["Junk removal", "Demolition", "Yard waste", "Appliances", "Cleanouts"],
    needs: ["furniture", "appliances", "cleanout", "construction"],
    coverage: [],
    images: [],
  },
  {
    slug: "dan-the-man-haul-away",
    name: "Dan The Man Haul Away",
    url: "https://danthemanhaulaway.com/",
    phone: "(619) 277-9569",
    email: null,
    address: "Santee, CA",
    hours: "Their site says open daily",
    blurb:
      "Family-run junk removal, dumpsters, and bobcat work based in Santee. Text a photo of the pile to (619) 277-9569. The site says all of San Diego County.",
    specialties: ["Junk removal", "Dumpster rental", "Bobcat", "Concrete", "Same-day"],
    needs: ["same-day", "furniture", "construction", "cleanout"],
    coverage: "county",
    images: [
      "/haulers/dan-the-man-haul-away-photo-1.jpg",
      "/haulers/dan-the-man-haul-away-photo-3.jpg",
      "/haulers/dan-the-man-haul-away-photo-2.jpg",
    ],
  },
  {
    slug: "impact-environmental",
    name: "Impact Environmental Co",
    url: "https://impact-eco.com/",
    phone: "(619) 393-6265",
    email: "estimates@impact-eco.com",
    address: "507 Broadway Unit C, El Cajon, CA 92021",
    hours: "Seven days. The site says a three-hour morning or afternoon window.",
    blurb:
      "El Cajon demolition and junk removal company, CSLB #1101347. They publish a price list and say they recycle or donate 60–80% of a job. Book on their site or text the same number.",
    specialties: ["Demolition", "Junk removal", "Published pricing", "Recycling", "Hot tubs"],
    needs: ["construction", "cleanout", "furniture", "appliances", "commercial"],
    coverage: [
      "jamul",
      "alpine",
      "bonita",
      "cardiff",
      "carlsbad",
      "coronado",
      "encinitas",
      "escondido",
      "clairemont",
      "lakeside",
      "tierrasanta",
      "vista",
      "santee",
      "ramona",
      "poway",
      "oceanside",
      "4s-ranch",
      "mira-mesa",
      "chula-vista",
      "san-marcos",
      "mission-valley",
      "la-mesa",
      "la-jolla",
      "el-cajon",
      "del-mar",
      "san-ysidro",
      "otay-mesa",
      "north-park",
      "point-loma",
      "linda-vista",
      "national-city",
      "kearny-mesa",
      "carmel-valley",
      "imperial-beach",
      "eastlake",
      "lemon-grove",
      "ocean-beach",
      "mission-beach",
      "pacific-beach",
      "university-city",
      "scripps-ranch",
      "rancho-bernardo",
      "rancho-santa-fe",
      "rancho-penasquitos",
      "downtown",
      "rancho-san-diego",
    ],
    images: ["/haulers/impact-environmental-photo-1.webp"],
  },
  {
    slug: "junk-and-trash-hauling",
    name: "Junk and Trash Hauling San Diego",
    url: null,
    phone: "(619) 908-0333",
    email: null,
    address: "1041 Market St Unit 219, San Diego, CA 92101",
    hours: null,
    blurb:
      "Downtown listing matched to this phone. A website was not confirmed. One domain that came up in search redirected to an unrelated roofer and is not linked.",
    specialties: ["Junk removal"],
    needs: [],
    coverage: [],
    images: [],
  },
  {
    slug: "top-tier-junk-removal",
    name: "Top Tier Junk Removal",
    url: "https://toptierjunkremoval.com/",
    phone: "(858) 428-5014",
    email: null,
    address: "15175 Segovia Ct, San Diego, CA 92129",
    hours: "Mon–Sat, 9:00 AM – 5:00 PM. Sunday closed.",
    blurb:
      "The site at this phone offers junk removal with eco-friendly disposal and says you can book online and save $20.",
    specialties: ["Junk removal", "Online booking"],
    needs: [],
    coverage: [],
    images: [],
  },
  {
    slug: "titos-junk-removal",
    name: "Tito's Junk Removal San Diego",
    url: null,
    phone: "(619) 466-6723",
    email: null,
    address: "761 Sunnyside Ave, San Diego, CA 92114",
    hours: null,
    blurb:
      "Phone matches Tito’s Hauling, owner Adrian Herrera, on local directories and a USDOT filing. titosjunkremoval.com lists a different number, (619) 666-0561, so that site is not used here.",
    specialties: ["Junk removal"],
    needs: ["furniture", "appliances", "cleanout"],
    coverage: [],
    images: [],
  },
  {
    slug: "coastline-hauling",
    name: "Coastline Hauling & Clean Up",
    url: null,
    phone: "(858) 265-8680",
    email: null,
    address: null,
    hours: "Yelp: Mon 5:30 AM – 11:00 PM; Tue–Sun 6:00 AM – 11:00 PM",
    blurb:
      "Yelp listing for this phone, owner Victor O. Licensed trash and debris removal, kitchen and bath demolition, estate and property cleanouts, spas, dirt, and concrete. Street addresses on other directories do not agree, so none is shown.",
    specialties: ["Demolition", "Cleanouts", "Junk removal", "Concrete"],
    needs: ["cleanout", "construction"],
    coverage: [],
    images: [],
  },
  {
    slug: "jakes-junk-removal",
    name: "Jake's Junk Removal and Demolition",
    url: "https://jakesjunkremoval.com/",
    phone: "(619) 723-6701",
    email: "jakesjunkremovalsd@gmail.com",
    address: "3158 Aurora Vista Dr, Spring Valley, CA 91978",
    hours: null,
    blurb:
      "Family-owned hauler. Their site says they have served San Diego since 2017, price by truck volume, and text a picture for a quote. The homepage lists household junk, construction debris, yard waste, and cleanouts. It does not describe demolition.",
    specialties: ["Furniture", "Construction debris", "Yard waste", "Cleanouts", "Since 2017"],
    needs: ["furniture", "construction", "cleanout"],
    coverage: [
      "santee",
      "carmel-valley",
      "rancho-santa-fe",
      "rancho-penasquitos",
      "rancho-bernardo",
      "tierrasanta",
      "normal-heights",
      "encinitas",
      "chula-vista",
    ],
    images: [],
  },
  {
    slug: "247-junk-removal",
    name: "24/7 Junk Removal LLC",
    url: "https://www.24-7-junkremoval.com/",
    phone: "(760) 820-5865",
    email: "CustomerService@24-7-JunkRemoval.com",
    address: "3223 Greyling Drive #23672, San Diego, CA 92193",
    hours: "24 hours, 7 days",
    blurb:
      "Owners Gavin Hartman and Benjamin Starr. In-home and discounted curbside pickup. Price is how full their 12 by 8 by 4 foot trailer gets, not an hourly rate. Text a photo to the same number.",
    specialties: ["24/7", "Curbside", "In-home", "Volume pricing"],
    needs: ["furniture", "cleanout", "same-day"],
    coverage: [],
    images: ["/haulers/247-junk-removal-photo-2.jpg"],
  },
  {
    slug: "triple-eee-haul-junk",
    name: "Triple EEE Haul Junk",
    url: null,
    phone: "(619) 519-3300",
    email: null,
    address: "San Diego, CA 92104",
    hours: "Mon–Sat 7:00 AM – 9:00 PM. Sunday closed.",
    blurb:
      "Yelp listing for this phone in North Park. Estate, storage, garage, attic, and basement cleanouts, plus appliances, furniture, and yard waste. The listing is marked Latinx-owned and includes dumpster rental. Their directory website did not resolve.",
    specialties: ["Cleanouts", "Appliances", "Furniture", "Yard waste", "Dumpster rental"],
    needs: ["cleanout", "furniture", "appliances"],
    coverage: ["north-park"],
    images: [],
  },
  {
    slug: "junkinator",
    name: "Junkinator Hauling Services",
    url: null,
    phone: "(858) 200-7130",
    email: null,
    address: "2676 Burgener Blvd, San Diego, CA 92110",
    hours: null,
    blurb:
      "A federal motor-carrier filing for Junkinator lists this phone and a Kearny Mesa address under Ross G. Gardner. A separate public profile names owner Tucker B. and says the company was established in 1999. No website was confirmed for this number.",
    specialties: ["Junk removal"],
    needs: [],
    coverage: [],
    images: [],
  },
  {
    slug: "clear-space-junk",
    name: "Clear Space Junk Solutions",
    url: null,
    phone: "(760) 871-3279",
    email: "Csjsolutions1@gmail.com",
    address: "456 Blue Sage Way, Oceanside, CA 92057",
    hours: "A Yahoo listing says open 24 hours",
    blurb:
      "Oceanside hauler at this phone, owner Alberto “Beto” Lozada. Residential and commercial junk removal, property cleanouts, and light demolition in North County. A Thumbtack answer says basic hauling starts at $160 including the dump fee.",
    specialties: ["North County", "Cleanouts", "Light demolition"],
    needs: ["cleanout", "construction", "north-county"],
    coverage: ["oceanside"],
    images: [],
  },
  {
    slug: "sd-haul-and-dump",
    name: "SD Haul & Dump LLC",
    url: null,
    phone: "(619) 977-1272",
    email: "info@sdhaulanddump.com",
    address: null,
    hours: null,
    blurb:
      "Yahoo listing for this phone says veteran-owned junk removal across San Diego County, from furniture pickups to property clearouts, with same-day service. This is not SD Hauling in Poway, which uses (619) 348-5865.",
    specialties: ["Veteran-owned", "Same-day", "Cleanouts", "Furniture"],
    needs: ["same-day", "furniture", "cleanout"],
    coverage: "county",
    images: [],
  },
  {
    slug: "american-haul-away",
    name: "American Haul Away",
    url: "https://www.americanhaulaway.com/",
    phone: "(858) 551-9376",
    email: null,
    address: null,
    hours: null,
    blurb:
      "Family-owned San Diego County hauler. The site also lists (619) 543-0375 and (760) 233-2033, says they have worked the county since 1993, and posts CSLB license 821997. Full-service junk removal starts at $65.",
    specialties: ["Since 1993", "Construction debris", "Yard waste", "Appliances", "Published pricing"],
    needs: ["furniture", "appliances", "construction", "cleanout", "commercial"],
    coverage: "county",
    images: [
      "/haulers/american-haul-away-photo-1.png",
      "/haulers/american-haul-away-photo-3.jpg",
    ],
  },
  {
    slug: "junk-seekers",
    name: "Junk Seekers",
    url: "https://junkseekers.com/",
    phone: "(619) 916-8419",
    email: null,
    address: "Spring Valley, CA",
    hours: "Mon–Sat, 8:00 AM – 8:00 PM. Sunday closed.",
    blurb:
      "Spring Valley company that says it serves all of San Diego County. Book a two-hour window online. They call about 30 minutes out, then price the load on site. Google Maps for this phone shows 5.0 from 95 reviews.",
    specialties: ["Appliances", "Furniture", "Yard waste", "Construction debris", "Hot tubs"],
    needs: ["furniture", "appliances", "construction", "cleanout", "same-day"],
    coverage: "county",
    images: ["/haulers/junk-seekers-photo-1.png"],
  },
  {
    slug: "fully-loaded-junk-removal",
    name: "Fully Loaded Junk Removal",
    url: null,
    phone: "(619) 920-5303",
    email: null,
    address: null,
    hours: null,
    blurb:
      "Only this phone is on file. fullyloadedjunkremoval.com publishes a different number, (619) 566-1983, so that site is not linked.",
    specialties: ["Junk removal"],
    needs: [],
    coverage: [],
    images: [],
  },
  {
    slug: "green-earth-usa",
    name: "Green Earth USA",
    url: null,
    phone: "(805) 490-1298",
    email: null,
    address: "7850 North Ave, Lemon Grove, CA 91945",
    hours: null,
    blurb:
      "Nextdoor lists Green Earth San Diego at this phone and address, owner Dylon. The page says they recycle, repurpose, and donate. A Thumbtack profile for Green Earth USA Inc in Santee lists junk removal, demolition, packing, and handyman work. Their own site was not confirmed.",
    specialties: ["Recycling", "Junk removal", "Demolition"],
    needs: ["furniture", "construction"],
    coverage: [],
    images: [],
  },
  {
    slug: "north-park-haulers",
    name: "North Park Haulers",
    url: null,
    phone: "(619) 808-4405",
    email: null,
    address: null,
    hours: "Yelp: Mon–Sat 8:00 AM – 6:00 PM; Sunday 9:00 AM – 5:00 PM",
    blurb:
      "Yelp listing for this phone: junk removal, construction debris cleanup, and material delivery, with same-day service available. A separate directory page uses different hours, so those hours are not shown.",
    specialties: ["North Park", "Construction debris", "Same-day"],
    needs: ["construction", "same-day", "furniture", "appliances"],
    coverage: ["north-park"],
    images: [],
  },
  {
    slug: "javier-junk-removal",
    name: "Javier Junk Removal & Concrete Work",
    url: null,
    phone: "(619) 886-8970",
    email: null,
    address: "4930 Genesee Ave, San Diego, CA 92117",
    hours: null,
    blurb:
      "Clairemont directory listings for this phone put the business at 4930 Genesee Ave. Hours on those pages do not match (7 AM–5 PM versus 6 AM–9 PM), so hours are left blank. The listed website was not confirmed.",
    specialties: ["Junk removal", "Concrete"],
    needs: ["construction"],
    coverage: [],
    images: [],
  },
  {
    slug: "johans-junk-removal",
    name: "Johan's Junk Removal & Hauling",
    url: "https://www.johansjunkremoval.com/",
    phone: "(619) 942-8978",
    email: "hello@johansjunkremoval.com",
    address: "San Diego, CA 92128",
    hours: "Mon–Sat 6:00 AM – 8:00 PM; Sunday 2:00 PM – 8:00 PM",
    blurb:
      "The site says they serve all of San Diego and haul furniture, appliances, mattresses, yard debris, construction debris, hot tubs, and cleanouts, except hazardous items. Yelp places them in Rancho Bernardo.",
    specialties: ["Furniture", "Appliances", "Cleanouts", "Hot tubs", "Construction debris"],
    needs: ["furniture", "appliances", "cleanout", "construction"],
    coverage: [],
    images: ["/haulers/johans-junk-removal-photo-1.png"],
  },
  {
    slug: "time-to-junk-it",
    name: "Time to Junk It",
    url: null,
    phone: "(619) 354-1042",
    email: null,
    address: "16855 Ralphs Ranch Rd, San Diego, CA 92127",
    hours: "Mon–Sat 8:00 AM – 8:00 PM. Sunday closed.",
    blurb:
      "Family-owned company run by Matt and Rose Spurr. Their Poway Chamber page says residential and commercial junk removal across San Diego County, including household items, greenery, construction debris, and appliances. They note they speak Spanish.",
    specialties: ["Family-owned", "Appliances", "Construction debris", "Yard waste"],
    needs: ["furniture", "appliances", "construction", "commercial"],
    coverage: "county",
    images: [],
  },
  {
    slug: "pugs-junk-removal",
    name: "Pug's Junk Removal",
    url: null,
    phone: "(858) 504-3745",
    email: null,
    address: null,
    hours: null,
    blurb:
      "Only this phone is on file. Public pages for a business named Pug’s Junk Removal use (858) 276-1722, so those sites are not linked.",
    specialties: ["Junk removal"],
    needs: [],
    coverage: [],
    images: [],
  },
  {
    slug: "clean-green-hauling",
    name: "Clean Green Hauling",
    url: "https://www.cghauling.com/",
    phone: "(858) 999-5477",
    email: "sd@cghauling.com",
    address: "North Pacific Beach, San Diego, CA",
    hours: "Mon–Fri, 6:00 AM – 5:00 PM",
    blurb:
      "Locally owned dumpster rental and junk removal. Their junk page says pricing starts at $99 for a full-size pickup and that they cover San Diego County. The dumpster page lists rentals from $625, extra tons at $185, and says they cannot take chemicals or paint.",
    specialties: ["Dumpster rental", "Junk removal", "Concrete", "Dirt", "Published pricing"],
    needs: ["construction", "furniture", "appliances", "cleanout"],
    coverage: "county",
    images: [],
  },
  {
    slug: "getridofit",
    name: "Getridofit.com San Diego",
    url: "https://getridofit.com/",
    phone: "(619) 780-2279",
    email: null,
    address: null,
    hours: null,
    blurb:
      "getridofit.com says they buy valuables and collections, not that they haul junk. The number printed on that homepage is 877-405-3165. The local number on file is not on that page.",
    specialties: ["Buys valuables"],
    needs: [],
    coverage: [],
    images: [],
  },
  {
    slug: "a-and-n-coastal-hauling",
    name: "A & N Coastal Hauling",
    url: "https://anhauling.com/",
    phone: "(619) 647-8154",
    email: null,
    address: "281 Durian St, Vista, CA 92083",
    hours: null,
    blurb:
      "A&N Coastal Hauling and Demolition. Their own X account posts this phone with anhauling.com. Locally owned demolition and junk removal in Vista, licensed and insured, with free estimates. They say they sort loads for recycling.",
    specialties: ["Demolition", "Junk removal", "Construction debris", "Appliances"],
    needs: ["construction", "furniture", "appliances", "north-county"],
    coverage: [
      "carlsbad",
      "clairemont",
      "del-cerro",
      "del-mar",
      "el-cajon",
      "encinitas",
      "escondido",
      "la-jolla",
      "lakeside",
      "la-mesa",
      "linda-vista",
      "mira-mesa",
      "mission-beach",
      "ocean-beach",
      "oceanside",
      "pacific-beach",
      "point-loma",
      "poway",
      "ramona",
      "rancho-bernardo",
      "rancho-penasquitos",
      "san-carlos",
      "san-marcos",
      "spring-valley",
      "santee",
      "vista",
    ],
    images: [],
  },
];

const bySlug = new Map(COMPANIES.map((c) => [c.slug, c]));

export function getCompany(slug: string): Company | undefined {
  const company = bySlug.get(slug);
  if (!company) return undefined;
  const extra = PROFILES[slug];
  const facts = FACTS[slug];
  return { ...company, ...extra, ...(facts ? { facts } : {}) };
}

export function companyServes(company: Company, community: Community): boolean {
  if (company.coverage === "county") return true;
  return company.coverage.includes(community.slug);
}

export function companiesForCommunity(community: Community): Company[] {
  return COMPANIES.filter((c) => companyServes(c, community));
}

export function communitiesForCompany(company: Company): Community[] {
  if (company.coverage === "county") return COMMUNITIES;
  const set = new Set(company.coverage);
  return COMMUNITIES.filter((c) => set.has(c.slug));
}

export function coverageLabel(company: Company): string {
  if (company.coverage === "county") return "San Diego County";
  if (company.coverage.length === 0) return "Confirm on their site";
  return `${company.coverage.length} listed communities`;
}
