export type ListingFacts = {
  /** Years in business, only when a site or public profile states it. */
  years: string | null;
  googleUrl: string | null;
  googleRating: string | null;
  googleReviews: string | null;
  yelpUrl: string | null;
  yelpReviews: string | null;
  bbbUrl: string | null;
  /** Yes, No, or Not listed. */
  onlineBooking: string;
  curbside: string;
  publishedPrices: string;
  /** Quotes a public page labels as Google reviews. */
  googleQuotes?: { author: string; text: string; place?: string }[];
};

const blank: ListingFacts = {
  years: null,
  googleUrl: null,
  googleRating: null,
  googleReviews: null,
  yelpUrl: null,
  yelpReviews: null,
  bbbUrl: null,
  onlineBooking: "Not listed",
  curbside: "Not listed",
  publishedPrices: "Not listed",
};

function fact(partial: Partial<ListingFacts>): ListingFacts {
  return { ...blank, ...partial };
}

export const FACTS: Record<string, ListingFacts> = {
  "freds-junk-removal": fact({
    googleRating: "5.0",
    googleReviews: "722 on Google Maps",
    years: "Since 2005. Their site says 21 years. A BBB file lists a 2009 start.",
    googleUrl: "https://g.page/r/Cf3-SV5xlZosEBM/review",
    yelpUrl: "https://www.yelp.com/biz/freds-junk-removal-san-diego-2",
    yelpReviews: "705 (5.0 on Yelp)",
    bbbUrl: "https://www.bbb.org/us/ca/chula-vista/profile/garbage-removal/freds-junk-removal-1126-171994186",
    onlineBooking: "Yes",
    curbside: "Yes",
    publishedPrices: "Yes",
  }),
  "jdog-junk-removal": fact({
    googleUrl: "https://www.google.com/maps?cid=15157132366364354932&hl=en",
    googleRating: "5.0",
    googleReviews: "309 on Google Maps",
    yelpUrl: "https://www.yelp.com/biz/jdog-junk-removal-and-hauling-san-diego-lemon-grove",
    yelpReviews: "50 (4.6 on the San Diego Yelp page)",
    onlineBooking: "Yes",
    curbside: "No",
    publishedPrices: "No",
  }),
  "junk-be-gone": fact({
    onlineBooking: "Yes",
    curbside: "No",
    publishedPrices: "No",
  }),
  "junk-punch": fact({
    years: "Founded September 2021",
    googleUrl: "https://maps.google.com/?cid=4982892038254218579",
    googleRating: "5.0",
    googleReviews: "204 on Google Maps",
    yelpUrl: "https://www.yelp.com/biz/junk-punch-junk-removal-chula-vista",
    yelpReviews: "20 (5.0 on Yelp)",
    onlineBooking: "Yes — a Book now button is on the site",
    curbside: "No",
    publishedPrices: "No",
  }),
  "the-wreckin-haul": fact({
    googleUrl: "https://www.google.com/maps?cid=3649343920810361382&hl=en",
    googleRating: "5.0",
    years: "California filing date July 13, 2023",
    yelpUrl: "https://www.yelp.com/biz/the-wreckin-haul-valley-center-2",
    yelpReviews: "5 (5.0 on Yelp)",
    onlineBooking: "No",
    curbside: "No — their site says they do not offer curb service",
    publishedPrices: "No",
    googleQuotes: [
      {
        author: "Mark D.",
        place: "Escondido",
        text: "These guys were incredible. Called on a Tuesday, they were at my house in Escondido by Thursday morning. Cleared out a full two-car garage worth of stuff — old furniture, shelving, boxes, you name it. Quoted me a fair price before they touched anything and stuck to it. Left the space spotless. Highly recommend.",
      },
      {
        author: "Sandra K.",
        place: "Valley Center",
        text: "We had to clear my mom's house in Valley Center after she passed. It was an emotional job and the team handled it with so much respect and professionalism. They were careful, kind and worked quickly without making us feel rushed. Everything was donated or responsibly disposed of. I can't say enough good things.",
      },
      {
        author: "Rob T.",
        place: "San Marcos",
        text: "Rented a dumpster for a full kitchen remodel in San Marcos. Drop-off was on time, pickup was when they said it would be, and the price was exactly what they quoted. No surprise fees. I manage multiple properties and I've already used The Wreckin' Haul on three jobs. These are my guys now.",
      },
    ],
  }),
  "junk-guys-san-diego": fact({
    years: "Their site says 13 years",
    googleUrl: "https://www.google.com/maps?cid=9954948730008415201&hl=en",
    googleRating: "5.0",
    googleReviews: "4 on Google Maps",
    yelpUrl: "https://www.yelp.com/biz/junk-guys-vista-2",
    onlineBooking: "Yes",
    curbside: "No",
    publishedPrices: "No",
  }),
  "dmd-junk-removal": fact({
    googleUrl: "https://www.google.com/maps?cid=15387267711353544730&hl=en",
    googleRating: "5.0",
    googleReviews: "9 on Google Maps",
    onlineBooking: "No",
    curbside: "No",
    publishedPrices: "Yes",
  }),
  "the-hauler": fact({
    googleUrl: "https://www.google.com/maps?cid=3770564203623245167&hl=en",
    googleRating: "5.0",
    googleReviews: "396 on Google Maps",
    yelpUrl: "https://www.yelp.com/biz/the-hauler-junk-removal-vista",
    yelpReviews: "80 (4.9 on Yelp)",
    onlineBooking: "Yes",
    curbside: "Yes",
    publishedPrices: "No",
  }),
  "ace-hauling": fact({
    googleUrl: "https://www.google.com/maps?cid=10793210614219976463&hl=en",
    googleRating: "4.9",
    googleReviews: "72 on Google Maps",
    years: "Since 2000. BBB lists 26 years.",
    yelpUrl: "https://www.yelp.com/biz/ace-hauling-junk-removal-and-demolition-carlsbad",
    yelpReviews: "31 (4.1 on Yelp)",
    bbbUrl: "https://www.bbb.org/us/ca/carlsbad/profile/clean-up-services/ace-hauling-junk-removal-demolition-1126-1065217",
    onlineBooking: "Quote form, not a time slot",
    curbside: "No",
    publishedPrices: "Yes — a per-ton disposal fee, not a full load chart",
  }),
  "junk-fairy": fact({
    googleUrl: "https://www.google.com/maps?cid=3948750656343301519&hl=en",
    googleRating: "5.0",
    years: "LLC filing date April 18, 2022",
    googleReviews: "130+ (their site, no star rating printed)",
    yelpUrl: "https://www.yelp.com/biz/junk-fairy-san-diego-2",
    yelpReviews: "117 (5.0 on Yelp)",
    onlineBooking: "Yes",
    curbside: "No",
    publishedPrices: "Yes",
  }),
  "haul-away-any-day": fact({
    googleUrl: "https://www.google.com/maps?cid=8386911639297676287&hl=en",
    googleRating: "5.0",
    googleReviews: "186 on Google Maps",
    years: "BBB start date March 14, 2022",
    yelpUrl: "https://www.yelp.com/biz/haul-away-any-day-el-cajon-3",
    yelpReviews: "76 (5.0 on Yelp)",
    bbbUrl: "https://www.bbb.org/us/ca/el-cajon/profile/junk-removal/haul-away-any-day-1126-1000160056",
    onlineBooking: "No — estimate request, not a scheduler",
    curbside: "No",
    publishedPrices: "No",
    googleQuotes: [
      {
        author: "Victor V.",
        text: "Super communicative and competitive pricing. Highly recommended. I needed some junk hauled away and they came through pretty quick. They left our yard looking brand new. No more ugly trash to look at.",
      },
      {
        author: "Joana V.",
        text: "Great overall experience with Haul Away Any Day! They answered my first call almost immediately. I sent them pictures of what I needed removed and they were able to give me a very affordable quote (best price I received)... Highly recommend and will absolutely use them again for any future junk removal needs.",
      },
      {
        author: "Chris R.",
        text: "We have used Haul Away Any Day three times at this point and it won’t be the last! Super friendly, understanding team and the process is so easy. I have done the full service as well as curbside. They are super responsive and dependable.",
      },
    ],
  }),
  junkmates: fact({
    googleUrl: "https://www.google.com/maps?cid=1321580647690588962&hl=en",
    googleRating: "5.0",
    years: "BBB start date January 5, 2022",
    yelpUrl: "https://www.yelp.com/biz/junkmates-encinitas",
    yelpReviews: "25 (4.9 on Yelp)",
    bbbUrl: "https://www.bbb.org/us/ca/encinitas/profile/junk-removal/junkmates-llc-1126-1000107710",
    onlineBooking: "Yes",
    curbside: "No",
    publishedPrices: "Yes — an FAQ range of $100–$140",
  }),
  "the-hauling-crew": fact({
    years: "Their site says the last 10 years",
    yelpUrl: "https://www.yelp.com/biz/the-hauling-crew-san-diego",
    yelpReviews: "37 (5.0 on Yelp)",
    onlineBooking: "No",
    curbside: "Yes — their Yelp page mentions a curbside discount",
    publishedPrices: "No",
  }),
  "jb-solutions": fact({
    googleUrl: "https://www.google.com/maps?cid=1678283388145385557&hl=en",
    googleRating: "5.0",
    googleReviews: "161 on Google Maps",
    yelpUrl: "https://www.yelp.com/biz/j-and-b-solutions-lakeside",
    yelpReviews: "11 (4.6 on the Lakeside Yelp page)",
    onlineBooking: "No",
    curbside: "No",
    publishedPrices: "No",
  }),
  "ruiz-junk-removal": fact({
    googleUrl: "https://www.google.com/maps?cid=17454156193879550605&hl=en",
    googleRating: "5.0",
    googleReviews: "36 on Google Maps",
    onlineBooking: "No",
    curbside: "No",
    publishedPrices: "Yes",
  }),
  "sa-junk-haul": fact({
    googleUrl: "https://www.google.com/maps?cid=750753795154526551&hl=en",
    googleRating: "5.0",
    googleReviews: "279 on Google Maps",
    years: "Their site says serving North County since 2015",
    yelpUrl: "https://www.yelp.com/biz/sa-junk-haul-san-marcos",
    yelpReviews: "321 (5.0 on Yelp)",
    onlineBooking: "Yes",
    curbside: "Yes",
    publishedPrices: "No",
  }),
  "severin-hauling": fact({
    googleUrl: "https://g.page/r/CbxDDPSHK9sjEAE/review",
    googleRating: "5.0",
    googleReviews: "42 (printed on their site)",
    yelpUrl: "https://www.yelp.com/biz/severin-hauling-la-mesa",
    onlineBooking: "No",
    curbside: "No",
    publishedPrices: "Yes",
    googleQuotes: [
      {
        author: "Maria Rodriguez",
        place: "El Cajon",
        text: "Severin Hauling made a difficult time so much easier. They handled my mother's estate cleanout with compassion and professionalism. Everything was sorted, donated, or disposed of properly. Highly recommend!",
      },
    ],
  }),
  "haul-out": fact({
    yelpUrl: "https://www.yelp.com/biz/haul-out-junk-removal-carlsbad",
    yelpReviews: "3 (5.0 on Yelp; that listing is marked closed)",
    onlineBooking: "Yes",
    curbside: "Yes",
    publishedPrices: "Yes",
  }),
  "demo-diego": fact({
    googleUrl: "https://www.google.com/maps?cid=4396346727591153256&hl=en",
    googleRating: "1.0",
    years: "Their site says over 20 years of experience",
    onlineBooking: "No",
    curbside: "No",
    publishedPrices: "Yes — about $150 to $600",
  }),
  "the-junk-transporter": fact({
    googleUrl: "https://www.google.com/maps?cid=14962871790750146828&hl=en",
    googleRating: "5.0",
    yelpUrl: "https://www.yelp.com/biz/the-junk-transporter-ramona",
    yelpReviews: "21 (5.0 on Yelp)",
    onlineBooking: "No",
    curbside: "No",
    publishedPrices: "Yes",
  }),
  junkmd: fact({
    googleUrl: "https://www.google.com/maps?cid=16732290001028989257&hl=en",
    years: "Their site says family-owned since 2012. BBB lists a 2019 start.",
    googleRating: "5.0",
    googleReviews: "1448 on Google Maps",
    yelpUrl: "https://www.yelp.com/biz/junkmd-san-diego-2",
    yelpReviews: "222 (4.9 on Yelp)",
    bbbUrl: "https://www.bbb.org/us/ca/san-diego/profile/junk-removal/junkmd-1126-1000111049",
    onlineBooking: "Yes",
    curbside: "Yes",
    publishedPrices: "Yes",
    googleQuotes: [
      {
        author: "Hillary Hebert",
        place: "La Jolla",
        text: "Showed up on time, gave a flat price, and had my entire garage cleared in under an hour. The crew was friendly, careful with the walls, and even swept up after. Best $20 I ever saved with that first-appointment discount.",
      },
      {
        author: "Jackie Teague",
        place: "Pacific Beach",
        text: "We had a hot tub that nobody else would touch. David and his team came out, broke it down, and hauled it away in a single afternoon. No damage to the patio. Easiest project we've ever booked.",
      },
      {
        author: "p bono",
        place: "Clairemont",
        text: "Booked an appliance pickup the same day after my old fridge died. Two pros showed up exactly in the two-hour window, hauled the unit down a flight of stairs, and were gone in 15 minutes. Worth every dollar.",
      },
      {
        author: "Emily Brandt",
        place: "North Park",
        text: "Clemencia made the booking process so smooth. The crew followed up the next morning, gave me a flat price, and donated most of the furniture to a local charity. Highly recommend JunkMD+.",
      },
      {
        author: "Sean Yao",
        place: "Sorrento Valley",
        text: "Office cleanout for our small business — they worked after hours so we didn't lose a workday. Professional, COI on file with our landlord, and the price beat the other quote we got.",
      },
      {
        author: "Sharon Minor",
        place: "Carmel Valley",
        text: "Estate cleanout after my mom passed. The team was kind, respectful, and went room by room with us. They donated everything they could. I cried a little because they made what felt impossible actually doable.",
      },
    ],
  }),
  "priority-hauling": fact({
    googleUrl: "https://www.google.com/maps?cid=12843748138001807394&hl=en",
    googleRating: "5.0",
    googleReviews: "453 on Google Maps",
    yelpUrl: "https://www.yelp.com/biz/priority-hauling-san-diego-san-diego",
    yelpReviews: "19 (4.8 on Yelp)",
    onlineBooking: "Yes — a schedule form",
    curbside: "Yes",
    publishedPrices: "Yes",
  }),
  "pick-and-dump": fact({
    googleUrl: "https://www.google.com/maps?cid=9538392292917552386&hl=en",
    googleRating: "5.0",
    googleReviews: "187 on Google Maps",
    years: "Established in 2021, on their site",
    onlineBooking: "Yes",
    curbside: "No",
    publishedPrices: "No",
  }),
  "crisan-junk-removal": fact({
    googleUrl: "https://www.google.com/maps?cid=14596070408682819003&hl=en",
    googleRating: "4.9",
    googleReviews: "275 on Google Maps",
    years: "Founded in 2021. BBB start date December 30, 2021.",
    yelpUrl: "https://www.yelp.com/biz/crisan-junk-removal-san-diego",
    yelpReviews: "8 (5.0 on Yelp)",
    bbbUrl: "https://www.bbb.org/us/ca/san-diego/profile/junk-removal/crisan-junk-removal-1126-1000103246",
    onlineBooking: "Yes",
    curbside: "Yes",
    publishedPrices: "Yes",
  }),
  "jc-junk-removal": fact({
    googleUrl: "https://www.google.com/maps?cid=4675426938451191698&hl=en",
    googleRating: "5.0",
    years: "BBB start date March 6, 2023",
    yelpUrl: "https://www.yelp.com/biz/jc-junk-removal-services-san-diego",
    yelpReviews: "5 (5.0 on Yelp)",
    bbbUrl: "https://www.bbb.org/us/ca/san-diego/profile/junk-removal/jc-junk-removal-services-1126-1000130162",
    onlineBooking: "No",
    curbside: "No",
    publishedPrices: "Yes — starting at $89",
  }),
  "junk-junkys": fact({
    googleUrl: "https://www.google.com/maps?cid=2592527575708407478&hl=en",
    googleRating: "5.0",
    yelpUrl: "https://www.yelp.com/biz/junk-junkys-san-diego-5",
    yelpReviews: "9 (5.0 on Yelp)",
    onlineBooking: "Yes",
    curbside: "Yes",
    publishedPrices: "No",
  }),
  "bay-junk": fact({
    years: "Their San Diego page says over a decade of experience",
    yelpUrl: "https://www.yelp.com/biz/bay-junk-san-diego",
    onlineBooking: "Yes",
    curbside: "Yes",
    publishedPrices: "No",
  }),
  "junk-away-san-diego": fact({
    googleUrl: "https://www.google.com/maps?cid=806691642560721301&hl=en",
    googleRating: "5.0",
    yelpUrl: "https://www.yelp.com/biz/junk-away-solana-beach-2",
    yelpReviews: "5 (5.0 on Yelp)",
    onlineBooking: "Quote page, not a confirmed calendar",
    curbside: "No",
    publishedPrices: "No",
  }),
  "fast-pickup-junk": fact({
    googleUrl: "https://www.google.com/maps?cid=9944768907344736391&hl=en",
    googleRating: "5.0",
    googleReviews: "77 on Google Maps",
    onlineBooking: "No",
    curbside: "No",
    publishedPrices: "No",
  }),
  "flash-junk-removal": fact({
    googleUrl: "https://www.google.com/maps?cid=4676297411804717318&hl=en",
    googleRating: "5.0",
    googleReviews: "47 on Google Maps",
    yelpUrl: "https://www.yelp.com/biz/flash-junk-removal-vista",
    yelpReviews: "18 (4.8 on Yelp)",
    onlineBooking: "No",
    curbside: "No",
    publishedPrices: "Yes",
  }),
  "clear-junk-removal": fact({
    googleUrl: "https://www.google.com/maps?cid=29689359997295554&hl=en",
    googleRating: "5.0",
    years: "Their site says 25 years of experience. BBB lists a start of April 16, 2015.",
    yelpUrl: "https://www.yelp.com/biz/clear-junk-removal-escondido-5",
    yelpReviews: "155 (5.0 on Yelp)",
    bbbUrl: "https://www.bbb.org/us/ca/san-diego/profile/junk-removal/clear-junk-removal-1126-172014705",
    onlineBooking: "No",
    curbside: "No",
    publishedPrices: "No",
  }),
  "junk-rushed": fact({
    googleUrl: "https://www.google.com/maps?cid=11585366755558508427&hl=en",
    googleRating: "5.0",
    googleReviews: "25 on Google Maps",
    onlineBooking: "No",
    curbside: "No",
    publishedPrices: "No",
  }),
  "pacific-rim-junk": fact({
    googleUrl: "https://www.google.com/maps?cid=13507881897938245335&hl=en",
    googleRating: "5.0",
    years: "A carrier record lists December 27, 2022",
    yelpUrl: "https://www.yelp.com/biz/pacific-rim-junk-removal-encinitas",
    yelpReviews: "23 (5.0 on Yelp)",
    bbbUrl: "https://www.bbb.org/us/ca/encinitas/profile/junk-removal/pacific-rim-junk--1126-1000172340",
    onlineBooking: "Contact form. They say you can book online or by phone.",
    curbside: "No",
    publishedPrices: "No",
  }),
  "strong-hauling": fact({
    googleUrl: "https://www.google.com/maps?cid=8460930047476013504&hl=en",
    googleRating: "4.9",
    googleReviews: "371 on Google Maps",
    onlineBooking: "No",
    curbside: "No",
    publishedPrices: "No",
  }),
  "the-junkiez": fact({
    googleRating: "5.0",
    googleReviews: "100+ (their San Diego page)",
    onlineBooking: "Yes",
    curbside: "No — they say items do not need to be at the curb",
    publishedPrices: "Yes — starting at $99",
  }),
  "monarch-junk-removal": fact({
    onlineBooking: "Yes",
    curbside: "No",
    publishedPrices: "Yes",
  }),
  "fetch-junk": fact({
    googleUrl: "https://www.google.com/maps?cid=6402100733939779208&hl=en",
    googleRating: "4.9",
    googleReviews: "87 on Google Maps",
    years: "BBB start date March 23, 2022. Their about page has also said since 2017.",
    yelpUrl: "https://www.yelp.com/biz/fetch-junk-removal-la-mesa",
    yelpReviews: "27 (5.0 on Yelp)",
    bbbUrl: "https://www.bbb.org/us/ca/la-mesa/profile/junk-removal/fetch-junk-removal-1126-1000099667",
    onlineBooking: "Yes",
    curbside: "Yes",
    publishedPrices: "Yes",
  }),
  "you-call-it-we-haul-it": fact({
    googleUrl: "https://www.google.com/maps?cid=9044371564863597264&hl=en",
    googleRating: "4.9",
    googleReviews: "551 on Google Maps",
    years: "Their site says over six years",
    yelpUrl: "https://www.yelp.com/biz/you-call-it-we-haul-it-san-diego-6",
    yelpReviews: "520 (4.9 on Yelp)",
    onlineBooking: "Yes",
    curbside: "Yes",
    publishedPrices: "No",
  }),
  "junk-haul-team": fact({
    googleUrl: "https://www.google.com/maps?cid=17009119962446675678&hl=en",
    googleRating: "5.0",
    onlineBooking: "No",
    curbside: "No",
    publishedPrices: "No",
  }),
  "gabriels-junk-removal": fact({
    googleUrl: "https://www.google.com/maps?cid=14544494330612028344&hl=en",
    googleRating: "5.0",
    googleReviews: "147 on Google Maps",
    yelpUrl: "https://www.yelp.com/biz/gabriels-hauling-and-junk-removal-services-san-diego",
    yelpReviews: "613 (5.0 on Yelp)",
    onlineBooking: "A free-estimate form is on the site",
    curbside: "Not listed",
    publishedPrices: "No",
  }),
  "jakes-junk-removal": fact({
    years: "Their site says serving San Diego since 2017",
    googleUrl: "https://www.google.com/maps?cid=8127751241517804226&hl=en",
    googleRating: "5.0",
    googleReviews: "365 on Google Maps",
    yelpUrl: "https://www.yelp.com/biz/jakes-junk-removal-and-demo-san-diego",
    yelpReviews: "125 (4.9 on Yelp)",
    onlineBooking: "No — call or text a picture",
    curbside: "Not listed",
    publishedPrices: "No — priced by how much of the truck the load fills",
  }),
  "titos-junk-removal": fact({
    googleUrl: "https://www.google.com/maps?cid=7181804827238742422&hl=en",
    googleRating: "5.0",
    googleReviews: "120 on Google Maps",
    yelpUrl: "https://www.yelp.com/biz/titos-hauling-san-diego-5",
    yelpReviews: "181 (5.0 on Yelp)",
    onlineBooking: "Not listed",
    curbside: "Not listed",
    publishedPrices: "Not listed",
  }),
  "top-tier-junk-removal": fact({
    googleUrl: "https://www.google.com/maps?cid=257525762372862667&hl=en",
    googleRating: "5.0",
    googleReviews: "77 on Google Maps",
    yelpUrl: "https://www.yelp.com/biz/top-tier-junk-removal-san-diego",
    yelpReviews: "359 (5.0 on Yelp)",
    onlineBooking: "Yes — the site says book online and save $20",
    curbside: "Not listed",
    publishedPrices: "No",
  }),
  "gti-hauling": fact({
    years: "BBB file opened September 13, 2022. BBB lists 3 years in business.",
    yelpUrl: "https://www.yelp.com/biz/gti-hauling-san-diego-3",
    yelpReviews: "343 (4.9 on Yelp)",
    bbbUrl: "https://www.bbb.org/us/ca/san-diego/profile/junk-removal/gti-hauling-1126-1000101431",
    onlineBooking: "Not listed",
    curbside: "Not listed",
    publishedPrices: "No",
  }),
  "nicos-hauling": fact({
    yelpUrl: "https://www.yelp.com/biz/nicos-hauling-san-diego-3",
    yelpReviews: "386 (5.0 on the San Diego Yelp page)",
    onlineBooking: "Not listed",
    curbside: "Not listed",
    publishedPrices: "No",
  }),
  "dan-the-man-haul-away": fact({
    years: "The site says both “since 2011” and “Est. 2019.”",
    googleUrl: "https://www.google.com/maps?cid=497862142433455257&hl=en",
    googleRating: "4.7",
    googleReviews: "33 on Google Maps",
    yelpUrl: "https://www.yelp.com/biz/dan-the-man-haul-away-san-diego-2",
    yelpReviews: "419 (4.9 on Yelp)",
    onlineBooking: "Text a photo to (619) 277-9569",
    curbside: "Not listed",
    publishedPrices: "Yes",
  }),
  "impact-environmental": fact({
    years: "Yelp’s about text says serving San Diego since 2016. That same paragraph also says “seventh year,” which does not line up with 2016. The site does not state a founding year. CSLB #1101347 is on the site and on that Yelp page.",
    googleUrl: "https://www.google.com/maps?cid=7395525016117625997&hl=en",
    googleRating: "5.0",
    googleReviews: "509 on Google Maps",
    yelpUrl: "https://www.yelp.com/biz/impact-environmental-co-san-diego-2",
    yelpReviews: "329 (4.9 on Yelp)",
    onlineBooking: "Yes",
    curbside: "Not listed",
    publishedPrices: "Yes",
  }),
  "coastline-hauling": fact({
    googleUrl: "https://www.google.com/maps?cid=16284571283554881014&hl=en",
    googleRating: "5.0",
    googleReviews: "22 on Google Maps",
    yelpUrl: "https://www.yelp.com/biz/coastline-hauling-and-clean-up-san-diego",
    yelpReviews: "116 (5.0 on Yelp)",
    onlineBooking: "Not listed",
    curbside: "Not listed",
    publishedPrices: "No",
  }),
  "247-junk-removal": fact({
    googleUrl: "https://www.google.com/maps?cid=15493656471264096925&hl=en",
    googleRating: "4.9",
    googleReviews: "100 on Google Maps",
    yelpUrl: "https://www.yelp.com/biz/24-7-junk-removal-san-diego-6",
    yelpReviews: "98 (5.0 on Yelp)",
    onlineBooking: "Yes",
    curbside: "Yes — the site says curbside is discounted",
    publishedPrices: "No — priced by trailer space. Tires are $25 each with the rim.",
  }),
  "triple-eee-haul-junk": fact({
    googleUrl: "https://www.google.com/maps?cid=12064340906930497518&hl=en",
    googleRating: "5.0",
    googleReviews: "24 on Google Maps",
    yelpUrl: "https://www.yelp.com/biz/triple-eee-haul-junk-san-diego-3",
    yelpReviews: "10 (5.0 on Yelp)",
    onlineBooking: "Not listed",
    curbside: "Not listed",
    publishedPrices: "No",
  }),
  "american-haul-away": fact({
    years: "Their site says serving San Diego County since 1993",
    googleUrl: "https://www.google.com/maps?cid=17347670256953588175&hl=en",
    yelpUrl: "https://www.yelp.com/biz/american-haul-away-san-diego",
    yelpReviews: "16 (4.0 on Yelp)",
    onlineBooking: "Yes — a request-appointment form is on the site",
    curbside: "Not listed",
    publishedPrices: "Yes — full-service starts at $65",
  }),
  "junk-seekers": fact({
    googleUrl: "https://g.page/r/CTHaqlEiFKC0EBM/review",
    googleRating: "5.0",
    googleReviews: "95 on Google Maps",
    yelpUrl: "https://www.yelp.com/biz/junk-seekers-san-diego-2",
    yelpReviews: "35 (5.0 on Yelp)",
    onlineBooking: "Yes",
    curbside: "Not listed",
    publishedPrices: "No — the on-site quote is the price",
    googleQuotes: [
      {
        author: "Monika Demla",
        text: "They can help you move, too! I was really pleased with their service, super prompt and they took such great care of my things.",
      },
      {
        author: "Yolanda Britton",
        text: "Santiago was prompt in responding to my inquiry. Efficient and professional in getting my move completed. Great and fair pricing.",
      },
      {
        author: "Tochia Henry",
        text: "I used Junk Seekers to remove an old, ratty, oversized sofa. Communication was excellent, price was reasonable, and Santiago is very friendly and personable.",
      },
    ],
  }),
  "johans-junk-removal": fact({
    googleUrl: "https://www.google.com/maps?cid=6845721295728008832&hl=en",
    googleRating: "5.0",
    googleReviews: "321 on Google Maps",
    yelpUrl: "https://www.yelp.com/biz/johans-junk-removal-and-hauling-san-diego",
    yelpReviews: "18 (5.0 on Yelp)",
    onlineBooking: "No — call for an estimate",
    curbside: "Not listed",
    publishedPrices: "No",
  }),
  "clean-green-hauling": fact({
    googleUrl: "https://www.google.com/maps?cid=11431313967923745788&hl=en",
    googleRating: "4.3",
    googleReviews: "16 on Google Maps",
    yelpUrl: "https://www.yelp.com/biz/clean-green-hauling-san-diego-2",
    yelpReviews: "53 (4.8 on Yelp)",
    onlineBooking: "Yes",
    curbside: "Yes — curbside residential junk removal as available",
    publishedPrices: "Yes",
  }),
  "a-and-n-coastal-hauling": fact({
    googleUrl: "https://www.google.com/maps?cid=11948822363799389679&hl=en",
    googleRating: "5.0",
    googleReviews: "120 on Google Maps",
    onlineBooking: "Yes — a quote form is on the site",
    curbside: "Not listed",
    publishedPrices: "No",
  }),
  "junkinator": fact({
    googleUrl: "https://www.google.com/maps?cid=472706095677808637&hl=en",
    googleRating: "4.9",
    googleReviews: "1258 on Google Maps",
    onlineBooking: "Not listed",
    curbside: "Not listed",
    publishedPrices: "No",
  }),
  "acosta-services": fact({
    years: "Their site says over two decades",
    yelpUrl: "https://www.yelp.com/biz/acosta-services-san-diego-5",
    yelpReviews: "136 (5.0 on Yelp)",
    onlineBooking: "A contact form is on the site",
    curbside: "Not listed",
    publishedPrices: "No — 10% off for new customers",
  }),
  "no-limit-hauling": fact({
    yelpUrl: "https://www.yelp.com/biz/no-limit-hauling-san-diego",
    yelpReviews: "27 (4.9 on Yelp)",
    onlineBooking: "Yes — a quote form is on the site",
    curbside: "Yes — the truck says curbside pickup",
    publishedPrices: "The truck advertises mattress removal $30 and appliance removal $30",
  }),
  "rancho-removal": fact({
    onlineBooking: "Not listed — call or text (858) 325-5220",
    curbside: "Yes — small curbside from $99",
    publishedPrices: "Small curbside from $99. Half load $350–$450+. Full load $499–$699+.",
  }),
  "pick-ur-junk": fact({
    yelpUrl: "https://www.yelp.com/biz/pick-ur-junk-san-marcos-2",
    yelpReviews: "195 (5.0 on Yelp)",
    onlineBooking: "Text photos for a quote",
    curbside: "Not listed",
    publishedPrices: "Minimum $100. Quarter load $120–$180. Half $200–$280. Two-thirds $300–$400. Full $450–$500.",
  }),
  "fs-junk-hauling": fact({
    yelpUrl: "https://www.yelp.com/biz/fs-junk-hauling-san-marcos",
    yelpReviews: "136 (5.0 on Yelp)",
    onlineBooking: "A quote button is on the site",
    curbside: "Yes — curbside pickups are listed",
    publishedPrices: "No",
  }),
  "junk-n-haul": fact({
    yelpUrl: "https://www.yelp.com/biz/junk-n-haul-san-diego",
    yelpReviews: "40 (5.0 on Yelp)",
    onlineBooking: "Not listed",
    curbside: "Not listed",
    publishedPrices: "No",
  }),
  "low-cost-hauling": fact({
    googleRating: "5.0",
    googleReviews: "7 on Google",
    yelpUrl: "https://www.yelp.com/biz/low-cost-hauling-lakeside",
    yelpReviews: "87 (5.0 on Yelp)",
    onlineBooking: "Yes — a booking form is on the site",
    curbside: "Not listed",
    publishedPrices: "No",
  }),
  "franks-demo-and-hauling": fact({
    yelpUrl: "https://www.yelp.com/biz/franks-demo-and-hauling-escondido-3",
    yelpReviews: "85 (4.8 on Yelp)",
    onlineBooking: "Not listed",
    curbside: "Not listed",
    publishedPrices: "No",
  }),
  "asap-junk-hauling": fact({
    googleRating: "4.8",
    googleReviews: "23 on Google",
    yelpUrl: "https://www.yelp.com/biz/asap-junk-hauling-san-diego-5",
    yelpReviews: "122 (4.9 on Yelp)",
    onlineBooking: "Not listed — call (619) 581-0872",
    curbside: "Not listed — they say they pull junk from inside",
    publishedPrices: "No — first-time customers get 10% off",
  }),
};
