export type ListingFacts = {
  /** Years in business, only when a site or public profile states it. */
  years: string | null;
  googleUrl: string | null;
  googleRating: string | null;
  googleReviews: string | null;
  yelpUrl: string | null;
  yelpReviews: string | null;
  bbbUrl: string | null;
  /** Yes, No, or Not listed. */
  onlineBooking: string;
  curbside: string;
  publishedPrices: string;
};

const blank: ListingFacts = {
  years: null,
  googleUrl: null,
  googleRating: null,
  googleReviews: null,
  yelpUrl: null,
  yelpReviews: null,
  bbbUrl: null,
  onlineBooking: "Not listed",
  curbside: "Not listed",
  publishedPrices: "Not listed",
};

function fact(partial: Partial<ListingFacts>): ListingFacts {
  return { ...blank, ...partial };
}

export const FACTS: Record<string, ListingFacts> = {
  "freds-junk-removal": fact({
    years: "Since 2005. Their site says 21 years. A BBB file lists a 2009 start.",
    googleUrl: "https://g.page/r/Cf3-SV5xlZosEBM/review",
    yelpUrl: "https://www.yelp.com/biz/freds-junk-removal-san-diego-2",
    yelpReviews: "705 (5.0 on Yelp)",
    bbbUrl: "https://www.bbb.org/us/ca/chula-vista/profile/garbage-removal/freds-junk-removal-1126-171994186",
    onlineBooking: "Yes",
    curbside: "Yes",
    publishedPrices: "Yes",
  }),
  "jdog-junk-removal": fact({
    yelpUrl: "https://www.yelp.com/biz/jdog-junk-removal-and-hauling-san-diego-lemon-grove",
    yelpReviews: "50 (4.6 on the San Diego Yelp page)",
    onlineBooking: "Yes",
    curbside: "No",
    publishedPrices: "No",
  }),
  "junk-be-gone": fact({
    onlineBooking: "Yes",
    curbside: "No",
    publishedPrices: "No",
  }),
  "junk-punch": fact({
    years: "Founded September 2021",
    googleUrl: "https://maps.google.com/?cid=4982892038254218579",
    googleRating: "5.0",
    googleReviews: "197 (shown on their site next to a Google link)",
    yelpUrl: "https://www.yelp.com/biz/junk-punch-junk-removal-chula-vista",
    yelpReviews: "20 (5.0 on Yelp)",
    onlineBooking: "Yes — a Book now button is on the site",
    curbside: "No",
    publishedPrices: "No",
  }),
  "the-wreckin-haul": fact({
    years: "California filing date July 13, 2023",
    yelpUrl: "https://www.yelp.com/biz/the-wreckin-haul-valley-center-2",
    yelpReviews: "5 (5.0 on Yelp)",
    onlineBooking: "No",
    curbside: "No — their site says they do not offer curb service",
    publishedPrices: "No",
  }),
  "junk-guys-san-diego": fact({
    years: "Their site says 13 years",
    yelpUrl: "https://www.yelp.com/biz/junk-guys-vista-2",
    onlineBooking: "Yes",
    curbside: "No",
    publishedPrices: "No",
  }),
  "dmd-junk-removal": fact({
    googleRating: "5.0",
    googleReviews: "8 (printed on their site)",
    onlineBooking: "No",
    curbside: "No",
    publishedPrices: "Yes",
  }),
  "the-hauler": fact({
    yelpUrl: "https://www.yelp.com/biz/the-hauler-junk-removal-vista",
    yelpReviews: "80 (4.9 on Yelp)",
    onlineBooking: "Yes",
    curbside: "Yes",
    publishedPrices: "No",
  }),
  "ace-hauling": fact({
    years: "Since 2000. BBB lists 26 years.",
    yelpUrl: "https://www.yelp.com/biz/ace-hauling-junk-removal-and-demolition-carlsbad",
    yelpReviews: "31 (4.1 on Yelp)",
    bbbUrl: "https://www.bbb.org/us/ca/carlsbad/profile/clean-up-services/ace-hauling-junk-removal-demolition-1126-1065217",
    onlineBooking: "Quote form, not a time slot",
    curbside: "No",
    publishedPrices: "Yes — a per-ton disposal fee, not a full load chart",
  }),
  "junk-fairy": fact({
    years: "LLC filing date April 18, 2022",
    googleReviews: "130+ (their site, no star rating printed)",
    yelpUrl: "https://www.yelp.com/biz/junk-fairy-san-diego-2",
    yelpReviews: "117 (5.0 on Yelp)",
    onlineBooking: "Yes",
    curbside: "No",
    publishedPrices: "Yes",
  }),
  "haul-away-any-day": fact({
    years: "BBB start date March 14, 2022",
    yelpUrl: "https://www.yelp.com/biz/haul-away-any-day-el-cajon-3",
    yelpReviews: "76 (5.0 on Yelp)",
    bbbUrl: "https://www.bbb.org/us/ca/el-cajon/profile/junk-removal/haul-away-any-day-1126-1000160056",
    onlineBooking: "No — estimate request, not a scheduler",
    curbside: "No",
    publishedPrices: "No",
  }),
  junkmates: fact({
    years: "BBB start date January 5, 2022",
    yelpUrl: "https://www.yelp.com/biz/junkmates-encinitas",
    yelpReviews: "25 (4.9 on Yelp)",
    bbbUrl: "https://www.bbb.org/us/ca/encinitas/profile/junk-removal/junkmates-llc-1126-1000107710",
    onlineBooking: "Yes",
    curbside: "No",
    publishedPrices: "Yes — an FAQ range of $100–$140",
  }),
  "the-hauling-crew": fact({
    years: "Their site says the last 10 years",
    yelpUrl: "https://www.yelp.com/biz/the-hauling-crew-san-diego",
    yelpReviews: "37 (5.0 on Yelp)",
    onlineBooking: "No",
    curbside: "Yes — their Yelp page mentions a curbside discount",
    publishedPrices: "No",
  }),
  "jb-solutions": fact({
    yelpUrl: "https://www.yelp.com/biz/j-and-b-solutions-lakeside",
    yelpReviews: "11 (4.6 on the Lakeside Yelp page)",
    onlineBooking: "No",
    curbside: "No",
    publishedPrices: "No",
  }),
  "ruiz-junk-removal": fact({
    onlineBooking: "No",
    curbside: "No",
    publishedPrices: "Yes",
  }),
  "sa-junk-haul": fact({
    years: "Their site says serving North County since 2015",
    yelpUrl: "https://www.yelp.com/biz/sa-junk-haul-san-marcos",
    yelpReviews: "321 (5.0 on Yelp)",
    onlineBooking: "Yes",
    curbside: "Yes",
    publishedPrices: "No",
  }),
  "severin-hauling": fact({
    googleUrl: "https://g.page/r/CbxDDPSHK9sjEAE/review",
    googleRating: "5.0",
    googleReviews: "42 (printed on their site)",
    yelpUrl: "https://www.yelp.com/biz/severin-hauling-la-mesa",
    onlineBooking: "No",
    curbside: "No",
    publishedPrices: "Yes",
  }),
  "haul-out": fact({
    yelpUrl: "https://www.yelp.com/biz/haul-out-junk-removal-carlsbad",
    yelpReviews: "3 (5.0 on Yelp; that listing is marked closed)",
    onlineBooking: "Yes",
    curbside: "Yes",
    publishedPrices: "Yes",
  }),
  "demo-diego": fact({
    years: "Their site says over 20 years of experience",
    onlineBooking: "No",
    curbside: "No",
    publishedPrices: "Yes — about $150 to $600",
  }),
  "the-junk-transporter": fact({
    yelpUrl: "https://www.yelp.com/biz/the-junk-transporter-ramona",
    yelpReviews: "21 (5.0 on Yelp)",
    onlineBooking: "No",
    curbside: "No",
    publishedPrices: "Yes",
  }),
  junkmd: fact({
    years: "Their site says family-owned since 2012. BBB lists a 2019 start.",
    googleRating: "5.0",
    googleReviews: "1,396+ (their site)",
    yelpUrl: "https://www.yelp.com/biz/junkmd-san-diego-2",
    yelpReviews: "222 (4.9 on Yelp)",
    bbbUrl: "https://www.bbb.org/us/ca/san-diego/profile/junk-removal/junkmd-1126-1000111049",
    onlineBooking: "Yes",
    curbside: "Yes",
    publishedPrices: "Yes",
  }),
  "priority-hauling": fact({
    yelpUrl: "https://www.yelp.com/biz/priority-hauling-san-diego-san-diego",
    yelpReviews: "19 (4.8 on Yelp)",
    onlineBooking: "Yes — a schedule form",
    curbside: "Yes",
    publishedPrices: "Yes",
  }),
  "pick-and-dump": fact({
    years: "Established in 2021, on their site",
    onlineBooking: "Yes",
    curbside: "No",
    publishedPrices: "No",
  }),
  "crisan-junk-removal": fact({
    years: "Founded in 2021. BBB start date December 30, 2021.",
    yelpUrl: "https://www.yelp.com/biz/crisan-junk-removal-san-diego",
    yelpReviews: "8 (5.0 on Yelp)",
    bbbUrl: "https://www.bbb.org/us/ca/san-diego/profile/junk-removal/crisan-junk-removal-1126-1000103246",
    onlineBooking: "Yes",
    curbside: "Yes",
    publishedPrices: "Yes",
  }),
  "jc-junk-removal": fact({
    years: "BBB start date March 6, 2023",
    yelpUrl: "https://www.yelp.com/biz/jc-junk-removal-services-san-diego",
    yelpReviews: "5 (5.0 on Yelp)",
    bbbUrl: "https://www.bbb.org/us/ca/san-diego/profile/junk-removal/jc-junk-removal-services-1126-1000130162",
    onlineBooking: "No",
    curbside: "No",
    publishedPrices: "Yes — starting at $89",
  }),
  "junk-junkys": fact({
    yelpUrl: "https://www.yelp.com/biz/junk-junkys-san-diego-5",
    yelpReviews: "9 (5.0 on Yelp)",
    onlineBooking: "Yes",
    curbside: "Yes",
    publishedPrices: "No",
  }),
  "bay-junk": fact({
    years: "Their San Diego page says over a decade of experience",
    yelpUrl: "https://www.yelp.com/biz/bay-junk-san-diego",
    onlineBooking: "Yes",
    curbside: "Yes",
    publishedPrices: "No",
  }),
  "junk-away-san-diego": fact({
    yelpUrl: "https://www.yelp.com/biz/junk-away-solana-beach-2",
    yelpReviews: "5 (5.0 on Yelp)",
    onlineBooking: "Quote page, not a confirmed calendar",
    curbside: "No",
    publishedPrices: "No",
  }),
  "fast-pickup-junk": fact({
    onlineBooking: "No",
    curbside: "No",
    publishedPrices: "No",
  }),
  "flash-junk-removal": fact({
    yelpUrl: "https://www.yelp.com/biz/flash-junk-removal-vista",
    yelpReviews: "18 (4.8 on Yelp)",
    onlineBooking: "No",
    curbside: "No",
    publishedPrices: "Yes",
  }),
  "clear-junk-removal": fact({
    years: "Their site says 25 years of experience. BBB lists a start of April 16, 2015.",
    yelpUrl: "https://www.yelp.com/biz/clear-junk-removal-escondido-5",
    yelpReviews: "155 (5.0 on Yelp)",
    bbbUrl: "https://www.bbb.org/us/ca/san-diego/profile/junk-removal/clear-junk-removal-1126-172014705",
    onlineBooking: "No",
    curbside: "No",
    publishedPrices: "No",
  }),
  "junk-rushed": fact({
    onlineBooking: "No",
    curbside: "No",
    publishedPrices: "No",
  }),
  "pacific-rim-junk": fact({
    years: "A carrier record lists December 27, 2022",
    yelpUrl: "https://www.yelp.com/biz/pacific-rim-junk-removal-encinitas",
    yelpReviews: "23 (5.0 on Yelp)",
    bbbUrl: "https://www.bbb.org/us/ca/encinitas/profile/junk-removal/pacific-rim-junk--1126-1000172340",
    onlineBooking: "Contact form. They say you can book online or by phone.",
    curbside: "No",
    publishedPrices: "No",
  }),
  "strong-hauling": fact({
    onlineBooking: "No",
    curbside: "No",
    publishedPrices: "No",
  }),
  "the-junkiez": fact({
    googleRating: "5.0",
    googleReviews: "100+ (their San Diego page)",
    onlineBooking: "Yes",
    curbside: "No — they say items do not need to be at the curb",
    publishedPrices: "Yes — starting at $99",
  }),
  "monarch-junk-removal": fact({
    onlineBooking: "Yes",
    curbside: "No",
    publishedPrices: "Yes",
  }),
  "fetch-junk": fact({
    years: "BBB start date March 23, 2022. Their about page has also said since 2017.",
    yelpUrl: "https://www.yelp.com/biz/fetch-junk-removal-la-mesa",
    yelpReviews: "27 (5.0 on Yelp)",
    bbbUrl: "https://www.bbb.org/us/ca/la-mesa/profile/junk-removal/fetch-junk-removal-1126-1000099667",
    onlineBooking: "Yes",
    curbside: "Yes",
    publishedPrices: "Yes",
  }),
  "you-call-it-we-haul-it": fact({
    years: "Their site says over six years",
    yelpUrl: "https://www.yelp.com/biz/you-call-it-we-haul-it-san-diego-6",
    yelpReviews: "520 (4.9 on Yelp)",
    onlineBooking: "Yes",
    curbside: "Yes",
    publishedPrices: "No",
  }),
  "junk-haul-team": fact({
    onlineBooking: "No",
    curbside: "No",
    publishedPrices: "No",
  }),
};
