export const PROFILES: Record<
  string,
  { details: string[]; links: { label: string; href: string }[] }
> = {
  "freds-junk-removal": {
    details: [
      "Fred’s publishes a household price list, a truck-load page, and a price-guarantee page, and asks for a photo by text before a pickup.",
      "Service pages cover general junk, furniture, mattresses, appliances, TV and e-waste, exercise equipment, garage cleanouts, yard waste, remodel debris, and commercial jobs.",
      "The service-area section is organized by ZIP and neighborhood across the county.",
    ],
    links: [
      { label: "Services", href: "https://www.fredsjunkremoval.com/services" },
      { label: "What we haul", href: "https://www.fredsjunkremoval.com/what-we-haul" },
      { label: "Price list", href: "https://www.fredsjunkremoval.com/pricelist" },
      { label: "Truck loads", href: "https://www.fredsjunkremoval.com/truck-loads" },
      { label: "Price guarantee", href: "https://www.fredsjunkremoval.com/price-guarantee" },
      { label: "Furniture removal", href: "https://www.fredsjunkremoval.com/services/furniture" },
      { label: "Mattress removal", href: "https://www.fredsjunkremoval.com/services/mattress" },
      { label: "Appliance removal", href: "https://www.fredsjunkremoval.com/services/appliances" },
      { label: "TV and e-waste", href: "https://www.fredsjunkremoval.com/services/ewaste" },
      { label: "Garage cleanouts", href: "https://www.fredsjunkremoval.com/services/garage" },
      { label: "Yard waste", href: "https://www.fredsjunkremoval.com/services/yard" },
      { label: "Commercial", href: "https://www.fredsjunkremoval.com/services/commercial" },
    ],
  },
  "jdog-junk-removal": {
    details: [
      "JDog is a veteran-owned franchise built to create ownership and jobs for veterans and military families. The company says it runs on Respect, Integrity, and Trust, and that each location is licensed and insured.",
      "They advertise recycling, repurposing, reselling, and local donations, and say 60% to 80% of a load stays out of the landfill. Donated items can come with a tax-deductible receipt.",
      "Residential work includes single items such as furniture, mattresses, pianos, and hot tubs, plus whole-house, attic, garage, and estate cleanouts. Commercial work includes offices, warehouses, construction debris, and light demolition. They also list appliances, e-waste, scrap metal, tires, yard waste, household clutter, on-site dumpsters, and heavy hauls.",
      "Hazardous waste, paints, solvents, and automotive or mercury waste are restricted or need special handling. Electronics and refrigerant appliances can carry a surcharge.",
      "Pricing is upfront by volume and weight and includes labor, travel, transport, and disposal or recycling. Estimates are free before the work starts. Published ranges: 1/4 truck $175–$250, 1/2 truck $250–$350, 3/4 truck $350–$500, and a full truck $500–$700.",
      "The San Diego operation is owned by military-family brothers Ryan and Seamus Fitzpatrick. Phones listed are (844) 438-5364 and (760) 291-8917. Named areas include San Diego, La Jolla, Pacific Beach, Chula Vista, El Cajon, La Mesa, Escondido, Oceanside, Carlsbad, Encinitas, Poway, and surrounding communities.",
    ],
    links: [
      { label: "San Diego location", href: "https://www.jdogjunkremoval.com/locations/california/san-diego-junk-removal/" },
      { label: "Oceanside", href: "https://www.jdogjunkremoval.com/locations/california/oceanside-junk-removal/" },
      { label: "Escondido", href: "https://www.jdogjunkremoval.com/locations/california/escondido-junk-removal/" },
      { label: "Residential junk removal", href: "https://www.jdogjunkremoval.com/residential/" },
    ],
  },
  "junk-be-gone": {
    details: [
      "Junk Be Gone’s San Diego page lists full trash cleanups, hot tubs, furniture, appliances, mattresses, office and storage cleanouts, construction debris, yard waste, sheds, and pianos.",
      "Their site says they recycle a large share of each load and offers an online booking discount.",
      "A cost article on the site explains that price depends on the size and weight of the load. The contact block lists (657) 254-3058 and info@junkbegoneinc.com.",
    ],
    links: [
      { label: "San Diego junk removal", href: "https://junkbegoneinc.com/" },
      { label: "What junk removal costs", href: "https://junkbegoneinc.com/how-much-does-junk-removal-cost-in-san-diego/" },
    ],
  },
  "junk-punch": {
    details: [
      "Junk Punch is a family-owned crew that posts separate San Diego pages for furniture, couches, appliances, mattresses, e-waste, yard waste, sheds, and rental cleanouts.",
      "They also list commercial junk removal, attic cleanouts, cardboard recycling, and a how-we-price page.",
      "Hours posted on the site run early morning through evening, seven days.",
    ],
    links: [
      { label: "Junk removal services", href: "https://junk-punch.com/junk-removal-services/" },
      { label: "How we price", href: "https://junk-punch.com/how-we-price/" },
      { label: "Furniture haul-away", href: "https://junk-punch.com/furniture-haul-away-san-diego/" },
      { label: "Couch removal", href: "https://junk-punch.com/san-diego-couch-removal/" },
      { label: "Appliance removal", href: "https://junk-punch.com/appliances-removal-san-diego/" },
      { label: "Mattress removal", href: "https://junk-punch.com/san-diego-mattress-removal/" },
      { label: "E-waste", href: "https://junk-punch.com/e-waste-san-diego/" },
      { label: "Yard waste", href: "https://junk-punch.com/yard-waste-removal-san-diego/" },
      { label: "Commercial", href: "https://junk-punch.com/commercial-junk-removal/" },
      { label: "Bulk trash pickup", href: "https://junk-punch.com/san-diego-bulk-trash-pick-up/" },
    ],
  },
  "the-wreckin-haul": {
    details: [
      "The Wreckin’ Haul pairs junk removal with dumpster rental for North County, and the site says same-day service is available.",
      "Cleanout pages cover garages and attics, estates and foreclosures, offices, and retail or warehouse jobs.",
      "They also list hot tub and shed removal, yard waste, and both residential and construction dumpsters.",
    ],
    links: [
      { label: "Services", href: "https://www.thewreckinhaul.com/services" },
      { label: "Garage and attic cleanouts", href: "https://www.thewreckinhaul.com/garage-and-attic-cleanouts" },
      { label: "Estate cleanouts", href: "https://www.thewreckinhaul.com/estate-and-foreclosure-cleanouts" },
      { label: "Hot tub and shed removal", href: "https://www.thewreckinhaul.com/hot-tub-and-shed-removal" },
      { label: "Yard waste", href: "https://www.thewreckinhaul.com/yard-waste-and-storm-debris" },
      { label: "Dumpster rental", href: "https://www.thewreckinhaul.com/dumpster-rental" },
      { label: "Office cleanouts", href: "https://www.thewreckinhaul.com/office-cleanouts" },
    ],
  },
  "junk-guys-san-diego": {
    details: [
      "Junk Guys lists separate pages for estate, eviction, foreclosure, garage, and hoarding cleanups.",
      "They also publish a furniture-removal page and an online book-now form.",
      "Their homepage calls out the greater San Diego area, including Carlsbad, Vista, Oceanside, and Encinitas.",
    ],
    links: [
      { label: "Furniture removal", href: "https://www.junkguyssandiego.com/furniture-removal" },
      { label: "Garage clean up", href: "https://www.junkguyssandiego.com/garage-clean-up" },
      { label: "Estate clean up", href: "https://www.junkguyssandiego.com/estate-clean-up" },
      { label: "Hoarding clean up", href: "https://www.junkguyssandiego.com/hoarding-clean-up" },
      { label: "Eviction clean up", href: "https://www.junkguyssandiego.com/eviction-clean-up" },
      { label: "Foreclosure clean up", href: "https://www.junkguyssandiego.com/foreclosure-clean-up" },
      { label: "Book now", href: "https://www.junkguyssandiego.com/book-now" },
    ],
  },
  "dmd-junk-removal": {
    details: [
      "DMD rents dump trailers and also hauls junk. Service pages cover furniture, appliances, mattresses, garages, estates, hot tubs, construction debris, yard waste, tenant cleanouts, and hoarding cleanup.",
      "Area pages name Oceanside, Carlsbad, Encinitas, Cardiff, Solana Beach, Del Mar, and Escondido.",
      "Quotes can be requested by text to the number on the trailer. Pricing is a separate page from the rental page.",
    ],
    links: [
      { label: "Services", href: "https://www.dmdjunkremoval.com/services" },
      { label: "Furniture removal", href: "https://www.dmdjunkremoval.com/services/furniture-removal" },
      { label: "Appliance removal", href: "https://www.dmdjunkremoval.com/services/appliance-removal" },
      { label: "Mattress disposal", href: "https://www.dmdjunkremoval.com/services/mattress-disposal" },
      { label: "Garage cleanout", href: "https://www.dmdjunkremoval.com/services/garage-cleanout" },
      { label: "Hot tub removal", href: "https://www.dmdjunkremoval.com/services/hot-tub-removal" },
      { label: "Construction debris", href: "https://www.dmdjunkremoval.com/services/construction-debris-removal" },
      { label: "Yard waste", href: "https://www.dmdjunkremoval.com/services/yard-waste-removal" },
      { label: "Dumpster rental", href: "https://www.dmdjunkremoval.com/rental" },
      { label: "Pricing", href: "https://www.dmdjunkremoval.com/pricing" },
    ],
  },
  "the-hauler": {
    details: [
      "The Hauler publishes separate pages for bulk trash, garage clean-outs, appliances, construction cleanup, and e-waste.",
      "Hoarder-house and estate clean-out pages are listed on their own.",
      "Booking is a form on their site, and the truck door lists a North County phone.",
    ],
    links: [
      { label: "Bulk trash cleanup", href: "https://www.thehaulerjunkremoval.com/bulk-trash-cleanup-service" },
      { label: "Garage clean-out", href: "https://www.thehaulerjunkremoval.com/garage-clean-out" },
      { label: "Appliance removal", href: "https://www.thehaulerjunkremoval.com/appliance-removal" },
      { label: "Construction clean up", href: "https://www.thehaulerjunkremoval.com/construction-clean-up" },
      { label: "E-waste recycling", href: "https://www.thehaulerjunkremoval.com/e-waste-recycling" },
      { label: "Hoarder clean-out", href: "https://www.thehaulerjunkremoval.com/hoarder-house-clean-out" },
      { label: "Estate clean-out", href: "https://www.thehaulerjunkremoval.com/house-estate-clean-out" },
      { label: "Book now", href: "https://www.thehaulerjunkremoval.com/book-now" },
    ],
  },
  "ace-hauling": {
    details: [
      "Ace splits work between hauling and demolition. Hauling pages include furniture, spas, brush, dirt, and concrete.",
      "Demolition pages cover concrete, construction, landscape, residential tear-outs, and swimming pools.",
      "They also publish a pricing page and a free fill-dirt program.",
    ],
    links: [
      { label: "Junk removal", href: "https://www.acehauling.com/junk-removal/" },
      { label: "Furniture disposal", href: "https://www.acehauling.com/furniture-disposal/" },
      { label: "Spa and hot tub removal", href: "https://www.acehauling.com/spa-hot-tub-removal-services/" },
      { label: "Brush and green waste", href: "https://www.acehauling.com/brush-green-waste-removal-services/" },
      { label: "Dirt removal", href: "https://www.acehauling.com/dirt-removal-services/" },
      { label: "Concrete removal", href: "https://www.acehauling.com/concrete-removal-services/" },
      { label: "Demolition", href: "https://www.acehauling.com/demolition/" },
      { label: "Pool demolition", href: "https://www.acehauling.com/swimming-pool-demolition-removal-services/" },
      { label: "Pricing", href: "https://www.acehauling.com/pricing/" },
    ],
  },
  "junk-fairy": {
    details: [
      "Junk Fairy publishes San Diego pages for furniture removal, appliance disposal, and commercial waste. Those are the service pages on the site.",
      "The truck advertises a starting price, and the site has an about page plus an on-page pricing section.",
    ],
    links: [
      { label: "Furniture removal", href: "https://www.junkfairy.com/furniture-removal-san-diego" },
      { label: "Appliance disposal", href: "https://www.junkfairy.com/appliance-disposal-san-diego" },
      { label: "Commercial waste", href: "https://www.junkfairy.com/commercial-waste-services-san-diego" },
      { label: "About", href: "https://www.junkfairy.com/about-us" },
      { label: "Pricing", href: "https://www.junkfairy.com/#pricing" },
    ],
  },
  "haul-away-any-day": {
    details: [
      "Haul Away Any Day lists furniture, appliances, garage and yard piles, and tenant cleanouts, with same-day pickup called out.",
      "The site is a short set of pages: services, about, a no-obligation estimate form, and contact. There are no separate item URLs beyond the services page.",
    ],
    links: [
      { label: "Services", href: "https://haulawayanyday.com/services/" },
      { label: "About", href: "https://haulawayanyday.com/about-us/" },
      { label: "Free estimate", href: "https://haulawayanyday.com/free-no-obligation-estimate/" },
      { label: "Contact", href: "https://haulawayanyday.com/contact-us/" },
    ],
  },
  "junkmates": {
    details: [
      "JunkMates is based in Encinitas and says it covers San Diego County with same-day or next-day pickup.",
      "Service pages cover general junk, furniture, mattresses, appliances, yard and landscape waste, construction debris, construction-site cleanup, office and storage cleanouts, and dumpster rental.",
      "Their furniture page says pricing starts around $100 and depends on the piece, weight, and location. Dumpster sizes listed are 10, 15, 20, and 40 yard.",
      "Location pages name Del Mar, Encinitas, La Jolla, Rancho Santa Fe, Carlsbad, and downtown.",
    ],
    links: [
      { label: "General junk removal", href: "https://www.junkmatessd.com/general-junk-removal/" },
      { label: "Furniture removal", href: "https://www.junkmatessd.com/furniture-removal/" },
      { label: "Mattress removal", href: "https://www.junkmatessd.com/mattress-removal/" },
      { label: "Appliance disposal", href: "https://www.junkmatessd.com/appliances-disposal/" },
      { label: "Yard waste", href: "https://www.junkmatessd.com/yard-waste-removal/" },
      { label: "Construction debris", href: "https://www.junkmatessd.com/construction-debris-removal/" },
      { label: "Office and storage cleanout", href: "https://www.junkmatessd.com/office-house-and-storage-cleanout/" },
      { label: "Dumpster rental", href: "https://www.junkmatessd.com/dumpster-rental/" },
      { label: "Book an estimate", href: "https://www.junkmatessd.com/booking/" },
    ],
  },
  "the-hauling-crew": {
    details: [
      "The Hauling Crew’s junk-removal page covers appliances, furniture, electronics, hot tubs and jacuzzis, and mattresses, and says they try to donate or recycle before landfilling.",
      "They also publish dumpster rental and storage pages.",
    ],
    links: [
      { label: "Junk removal", href: "https://www.thehaulingcrewsd.com/junk-removal" },
      { label: "Dumpster rental", href: "https://www.thehaulingcrewsd.com/dumpster-rental" },
      { label: "Storage", href: "https://www.thehaulingcrewsd.com/storage" },
      { label: "About", href: "https://www.thehaulingcrewsd.com/aboutus" },
      { label: "Contact", href: "https://www.thehaulingcrewsd.com/contact" },
    ],
  },
  "jb-solutions": {
    details: [
      "J&B Solutions is a Lakeside hauler that says it covers Lakeside, El Cajon, Santee, and the rest of San Diego County.",
      "Their pages cover junk hauling, home clean-outs (including estates), construction debris, and both residential and commercial dumpster rental. A 20-yard and a 30-yard size are described.",
      "The site says the company is licensed and insured and offers one-time or scheduled pickups.",
    ],
    links: [
      { label: "Junk removal", href: "https://jandbsolutionsca.com/best-junk-removal-in-lakeside-el-cajon-santee-and-all-of-san-diego-county/" },
      { label: "Home clean-out", href: "https://jandbsolutionsca.com/home-clean-out-in-lakeside-el-cajon-santee-and-all-of-san-diego-county/" },
      { label: "Commercial dumpster rental", href: "https://jandbsolutionsca.com/commercial-dumpster-rental-in-lakeside-el-cajon-santee-and-all-of-san-diego-county/" },
    ],
  },
  "ruiz-junk-removal": {
    details: [
      "Ruiz is a single-page San Diego site. The page describes junk removal, property cleanouts, trash hauling, and demo debris, and asks you to upload photos for an estimate.",
      "Keywords on the page also name furniture and appliance hauling. There are no separate service URLs to link.",
      "The page lists (619) 253-3200 and Ruizjunkremoval.hauling@gmail.com.",
    ],
    links: [],
  },
  "sa-junk-haul": {
    details: [
      "SA Junk Haul’s San Diego page sits next to residential, commercial, apartment, and office cleanout pages.",
      "They also publish furniture disposal, appliance removal, and mattress disposal pages.",
    ],
    links: [
      { label: "San Diego service area", href: "https://sajunkhaul.com/service-area/san-diego-ca/" },
      { label: "Services", href: "https://sajunkhaul.com/services/" },
      { label: "Residential", href: "https://sajunkhaul.com/reliable-residential-junk-removal-services/" },
      { label: "Commercial", href: "https://sajunkhaul.com/professional-commercial-junk-removal-services/" },
      { label: "Apartment cleanout", href: "https://sajunkhaul.com/professional-apartment-cleanout-services/" },
      { label: "Furniture disposal", href: "https://sajunkhaul.com/furniture-disposal-services/" },
      { label: "Appliance removal", href: "https://sajunkhaul.com/appliance-removal-services/" },
      { label: "Mattress disposal", href: "https://sajunkhaul.com/mattress-disposal-services/" },
    ],
  },
  "severin-hauling": {
    details: [
      "Severin publishes item-style pricing, a same-day page, and a cost page for San Diego junk removal.",
      "Dedicated pages cover furniture, couches, appliances, estate cleanouts, commercial jobs, construction debris, hoarding cleanup, and hot tubs.",
      "The crew is based in La Mesa and lists countywide areas.",
    ],
    links: [
      { label: "Services", href: "https://www.severinhauling.com/services" },
      { label: "Pricing", href: "https://www.severinhauling.com/junk-removal-cost-san-diego" },
      { label: "Same-day pickup", href: "https://www.severinhauling.com/same-day-junk-removal-san-diego" },
      { label: "Furniture disposal", href: "https://www.severinhauling.com/furniture-disposal-san-diego" },
      { label: "Couch removal", href: "https://www.severinhauling.com/couch-removal-san-diego" },
      { label: "Appliance removal", href: "https://www.severinhauling.com/appliance-removal-san-diego" },
      { label: "Construction debris", href: "https://www.severinhauling.com/construction-debris-removal-san-diego" },
      { label: "Estate cleanout", href: "https://www.severinhauling.com/estate-cleanout-san-diego" },
      { label: "Commercial", href: "https://www.severinhauling.com/commercial-junk-removal-san-diego" },
      { label: "Hot tub removal", href: "https://www.severinhauling.com/hot-tub-removal-san-diego" },
    ],
  },
  "haul-out": {
    details: [
      "Haul Out splits residential and commercial hauling onto their own pages. The FAQ says they take furniture, appliances, electronics, yard debris, and construction materials, and that they will not take hazardous items such as chemicals, propane, or paint.",
      "Same-day and next-day pickup is listed when available, including weekends. The crew does the lifting from inside the house.",
      "The site describes a family- and veteran-owned San Diego crew.",
    ],
    links: [
      { label: "Residential hauling", href: "https://www.hauloutjunkremoval.com/residential-hauling-services" },
      { label: "Commercial hauling", href: "https://www.hauloutjunkremoval.com/commercial-hauling-services" },
      { label: "FAQs", href: "https://www.hauloutjunkremoval.com/faqs" },
      { label: "Construction debris guide", href: "https://www.hauloutjunkremoval.com/resources/residential-construction-debris-removal" },
      { label: "E-waste guide", href: "https://www.hauloutjunkremoval.com/resources/responsible-ewaste-recycling" },
      { label: "Contact", href: "https://www.hauloutjunkremoval.com/contact" },
    ],
  },
  "demo-diego": {
    details: [
      "Demo Diego’s junk pages cover furniture, appliances, estate cleanouts, yard waste, hot tubs, foreclosure cleanouts, construction debris, and same-day pickup.",
      "Separate demolition pages cover pools, concrete, kitchens, bathrooms, decks, and commercial tear-outs. Commercial pages also list daily junk, weekly waste, and construction-site cleanup.",
    ],
    links: [
      { label: "Junk removal", href: "https://www.demodiego.com/junk-removal" },
      { label: "Furniture removal", href: "https://www.demodiego.com/junk-removal/furniture-removal" },
      { label: "Appliance removal", href: "https://www.demodiego.com/junk-removal/appliance-removal" },
      { label: "Estate cleanout", href: "https://www.demodiego.com/junk-removal/estate-cleanout" },
      { label: "Hot tub removal", href: "https://www.demodiego.com/junk-removal/hot-tub-removal" },
      { label: "Construction debris", href: "https://www.demodiego.com/junk-removal/construction-debris-removal" },
      { label: "Same-day junk removal", href: "https://www.demodiego.com/junk-removal/same-day-junk-removal" },
      { label: "Pool demolition", href: "https://www.demodiego.com/demolition/pool-demolition" },
      { label: "Pricing", href: "https://www.demodiego.com/pricing" },
    ],
  },
  "the-junk-transporter": {
    details: [
      "The Junk Transporter posts load prices: minimum from $90, mattress from $99, spa removal $350, a quarter truck $220, a half truck $350, and a full dump truck $550.",
      "Their services page lists yard debris, remodeling and construction trash, estate and foreclosure cleanouts, garage and attic cleanouts, storage and office junk, and items such as appliances, furniture, hot tubs, sheds, and yard waste.",
      "Separate pages cover move-in and move-out junk, home remodeling debris, jacuzzi and spa removal, yard waste, and landscape waste.",
    ],
    links: [
      { label: "Services we provide", href: "https://thejunktransporter.com/services-we-provide-1" },
      { label: "Pricing", href: "https://thejunktransporter.com/pricing" },
      { label: "Move-in and move-out", href: "https://thejunktransporter.com/move-in%2Fout-home-junk" },
      { label: "Home remodeling", href: "https://thejunktransporter.com/home-remodeling" },
      { label: "Jacuzzi and spa removal", href: "https://thejunktransporter.com/jacuzzi-spa-junk-removal" },
      { label: "Yard waste", href: "https://thejunktransporter.com/yard-waste-junk-hauling" },
      { label: "Landscape waste", href: "https://thejunktransporter.com/landscape-waste-removal" },
      { label: "FAQ", href: "https://thejunktransporter.com/faq" },
    ],
  },
  junkmd: {
    details: [
      "JunkMD says it has been family-owned since 2012 and posts flat-rate pricing with same-day and next-day options.",
      "Beyond the residential, commercial, and demolition hubs, the site has pages for furniture, appliances, mattresses, hot tubs, estates, hoarder and foreclosure cleanouts, garages, attics, and yard waste.",
    ],
    links: [
      { label: "Junk removal services", href: "https://junkmd.com/junk-removal-services" },
      { label: "Residential", href: "https://junkmd.com/residential-junk-removal" },
      { label: "Commercial", href: "https://junkmd.com/commercial-junk-removal" },
      { label: "Furniture removal", href: "https://junkmd.com/furniture-removal" },
      { label: "Appliance removal", href: "https://junkmd.com/appliance-removal" },
      { label: "Mattress disposal", href: "https://junkmd.com/mattress-disposal" },
      { label: "Hot tub removal", href: "https://junkmd.com/hot-tub-removal" },
      { label: "Estate cleanout", href: "https://junkmd.com/estate-cleanout" },
      { label: "Garage cleanout", href: "https://junkmd.com/garage-cleanout" },
      { label: "Pricing", href: "https://junkmd.com/pricing" },
    ],
  },
  "priority-hauling": {
    details: [
      "Priority Hauling publishes a San Diego pricing page plus pages for furniture and couches, mattresses, appliances, e-waste, carpet, and construction debris.",
      "Cleanout pages cover storage, garages, apartments, moving, and hoarder houses, aimed at San Diego, Chula Vista, and National City. They also list spa and hot tub removal, shed removal, and dumpster rental.",
    ],
    links: [
      { label: "Pricing", href: "https://www.priorityhaulingsd.com/junkremovalpricinginsandiegochulavistanationalcity" },
      { label: "Furniture and couch removal", href: "https://www.priorityhaulingsd.com/furnitureandcouchremoval" },
      { label: "Appliance removal", href: "https://www.priorityhaulingsd.com/applianceremovalsandiego" },
      { label: "Mattress removal", href: "https://www.priorityhaulingsd.com/mattressremovalsandiego" },
      { label: "E-waste recycling", href: "https://www.priorityhaulingsd.com/ewasterecyclingsandiegochulavistanationalcity" },
      { label: "Construction debris", href: "https://www.priorityhaulingsd.com/construction-debris" },
      { label: "Hot tub removal", href: "https://www.priorityhaulingsd.com/spahottubremovalsandiego" },
      { label: "Garage cleanout", href: "https://www.priorityhaulingsd.com/garagecleanoutservicessandiego" },
      { label: "Hoarder house cleanup", href: "https://www.priorityhaulingsd.com/hoarderhousecleanupsandiego" },
      { label: "Dumpster rental", href: "https://www.priorityhaulingsd.com/dumpsterrentalsandiego" },
    ],
  },
  "pick-and-dump": {
    details: [
      "Pick and Dump has standalone pages for furniture, patio furniture, appliances, mattresses, yard waste, and water heaters.",
      "Cleanout pages cover houses, apartments, garages, storage units, hoarder houses, offices, and trash enclosures, plus commercial junk removal.",
    ],
    links: [
      { label: "Junk removal", href: "https://www.pickanddump.com/junk-removal-service" },
      { label: "Furniture removal", href: "https://www.pickanddump.com/furniture-removal" },
      { label: "Appliance removal", href: "https://www.pickanddump.com/appliance-removal" },
      { label: "Mattress removal", href: "https://www.pickanddump.com/mattress-removal" },
      { label: "Yard waste", href: "https://www.pickanddump.com/yard-waste-removal" },
      { label: "Garage cleanout", href: "https://www.pickanddump.com/garage-cleanout" },
      { label: "House cleanout", href: "https://www.pickanddump.com/house-cleanout-service" },
      { label: "Apartment cleanout", href: "https://www.pickanddump.com/apartment-cleanout" },
      { label: "Storage unit cleanout", href: "https://www.pickanddump.com/storage-unit-cleanout" },
      { label: "Commercial", href: "https://www.pickanddump.com/commercial-junk-removal" },
    ],
  },
  "crisan-junk-removal": {
    details: [
      "Crisan publishes residential, commercial, and cleanout hubs plus item pages for appliances, furniture, mattresses, yard waste, hot tubs, and RVs.",
      "Other pages cover garage and attic cleanouts, estate cleanouts, office cleanouts, and a pricing page.",
    ],
    links: [
      { label: "Services", href: "https://crisanjunkremoval.com/services/" },
      { label: "Pricing", href: "https://crisanjunkremoval.com/pricing/" },
      { label: "Residential", href: "https://crisanjunkremoval.com/residential-junk-removal/" },
      { label: "Furniture removal", href: "https://crisanjunkremoval.com/furniture-removal/" },
      { label: "Appliance removal", href: "https://crisanjunkremoval.com/appliance-removal/" },
      { label: "Mattress removal", href: "https://crisanjunkremoval.com/mattress-removal/" },
      { label: "Hot tub removal", href: "https://crisanjunkremoval.com/hot-tub-removal/" },
      { label: "Yard waste", href: "https://crisanjunkremoval.com/yard-waste-removal/" },
      { label: "Garage cleanouts", href: "https://crisanjunkremoval.com/garage-cleanouts/" },
      { label: "Estate cleanouts", href: "https://crisanjunkremoval.com/estate-cleanouts-san-diego/" },
    ],
  },
  "jc-junk-removal": {
    details: [
      "JC Junk Removal lists furniture, appliances, mattresses, garage cleanouts, yard cleanouts, real-estate cleanouts, sheds, scrap, and hot tub removal.",
      "An office furniture and equipment page sits alongside the household pages. City pages cover National City, Chula Vista, La Mesa, and nearby South Bay and East County cities.",
    ],
    links: [
      { label: "Services", href: "https://jcjunkremovalservices.com/services/" },
      { label: "Furniture removal", href: "https://jcjunkremovalservices.com/furniture-removal/" },
      { label: "Appliance removal", href: "https://jcjunkremovalservices.com/appliance-removal/" },
      { label: "Mattress removal", href: "https://jcjunkremovalservices.com/mattress-removal/" },
      { label: "Garage cleanout", href: "https://jcjunkremovalservices.com/garage-cleanout/" },
      { label: "Yard cleanout", href: "https://jcjunkremovalservices.com/yard-cleanout/" },
      { label: "Real estate cleanout", href: "https://jcjunkremovalservices.com/real-estate-cleanout/" },
      { label: "Hot tub removal", href: "https://jcjunkremovalservices.com/hot-tub-removal/" },
      { label: "Shed removal", href: "https://jcjunkremovalservices.com/shed-removal/" },
      { label: "Office furniture", href: "https://jcjunkremovalservices.com/office-furniture-equipment-removal/" },
    ],
  },
  "junk-junkys": {
    details: [
      "Junk Junkys says it works across San Diego County and lists hours of 9 AM to 6 PM, seven days.",
      "The about page names furniture, mattresses, TVs, electronics, appliances, hot tubs, and yard waste for homes and offices.",
      "Service pages split residential waste, commercial cleaning, construction waste, and e-waste and appliances. Booking is a form on the site.",
    ],
    links: [
      { label: "Services", href: "https://junkjunkys.com/services/" },
      { label: "Residential waste", href: "https://junkjunkys.com/services/residential-waste/" },
      { label: "Commercial", href: "https://junkjunkys.com/services/commercial-cleaning/" },
      { label: "Construction waste", href: "https://junkjunkys.com/services/construction-cleaning/" },
      { label: "E-waste and appliances", href: "https://junkjunkys.com/services/e-waste-appliances/" },
      { label: "Locations", href: "https://junkjunkys.com/locations/" },
      { label: "Get a quote", href: "https://junkjunkys.com/get-quote/" },
    ],
  },
  "bay-junk": {
    details: [
      "Bay Junk’s San Diego page lists Solana Beach, Encinitas, Carmel Valley, Cardiff, Poway, La Jolla, La Mesa, El Cajon, Del Mar, Carlsbad, University City, and Rancho Bernardo.",
      "They also haul in the Bay Area, so the San Diego page is the one to use. The local text line on that page is (619) 488-6969.",
      "Shared service pages cover residential hauling, business hauling, cleanouts, furniture, mattresses, and items they take. Pricing is described as an upfront quote based on volume, weight, and access.",
    ],
    links: [
      { label: "San Diego junk removal", href: "https://www.bayjunk.com/locations/California/junk-removal-san-diego" },
      { label: "Residential services", href: "https://www.bayjunk.com/junk-removal/residential-services" },
      { label: "Business services", href: "https://www.bayjunk.com/junk-removal/business-services" },
      { label: "Cleanout services", href: "https://www.bayjunk.com/junk-removal/business-services/cleanout-services" },
      { label: "Furniture removal", href: "https://www.bayjunk.com/furniture-removal" },
      { label: "Mattress removal", href: "https://www.bayjunk.com/what-we-haul-away/mattress-removal" },
      { label: "Items we take", href: "https://www.bayjunk.com/what-we-haul-away/residential-items-we-take" },
      { label: "Pricing", href: "https://www.bayjunk.com/pricing" },
      { label: "How it works", href: "https://www.bayjunk.com/how-it-works" },
    ],
  },
  "junk-away-san-diego": {
    details: [
      "Junk Away publishes San Diego pages for apartments, appliances, furniture, offices, hotels, warehouses, property cleanouts, and storage units.",
      "Item pages cover couches, mattresses and beds, washers and dryers, refrigerators, and spa or hot tub removal. They also list garage cleanouts and dumpster rental.",
      "The homepage pitches same-day home and business hauling with upfront pricing.",
    ],
    links: [
      { label: "Furniture removal", href: "https://junkawaysandiego.com/furniture-removal-san-diego/" },
      { label: "Appliance removal", href: "https://junkawaysandiego.com/appliance-removal-san-diego/" },
      { label: "Mattress and bed", href: "https://junkawaysandiego.com/mattresss-bed/" },
      { label: "Hot tub and jacuzzi", href: "https://junkawaysandiego.com/spa-hot-tub-jacuzzi/" },
      { label: "Apartment cleanout", href: "https://junkawaysandiego.com/apartment-cleanout-san-diego/" },
      { label: "Garage cleanouts", href: "https://junkawaysandiego.com/garage-cleanouts/" },
      { label: "Office cleanout", href: "https://junkawaysandiego.com/office-cleanout-san-diego/" },
      { label: "Storage unit cleanout", href: "https://junkawaysandiego.com/storage-unit-cleanout-san-diego/" },
      { label: "Warehouse cleanout", href: "https://junkawaysandiego.com/warehouse-cleanout-san-diego/" },
      { label: "Dumpster rental", href: "https://junkawaysandiego.com/dumpster-rental/" },
    ],
  },
  "fast-pickup-junk": {
    details: [
      "Fast Pickup Junk is a single-page site for the San Diego metro. It lists junk, furniture, appliances, mattresses, dump runs, trash-outs, construction debris, property cleanouts, evictions, estates, hoarder cleanouts, garages, shed demolition, and hot tub demolition.",
      "The page says price is based on how much of the truck the load fills, and that same-day service is offered. Quotes go through the form on that page. No separate service URLs are published.",
    ],
    links: [],
  },
  "flash-junk-removal": {
    details: [
      "Flash lists countywide junk removal with a services hub, house cleanouts, hot tub removal, RV and motor-home removal, and dumpster rentals.",
      "City pages cover San Marcos, Solana Beach, Rancho Bernardo, Encinitas, Rancho Santa Fe, Oceanside, Escondido, Vista, Del Mar, and Fallbrook.",
      "Hours on the site are seven days, morning through evening, and they price by how full the truck is.",
    ],
    links: [
      { label: "Services", href: "https://www.flashjunkremoval.com/services" },
      { label: "House cleanouts", href: "https://www.flashjunkremoval.com/house-cleanouts-San-Diego-CA" },
      { label: "Hot tub removal", href: "https://www.flashjunkremoval.com/hot-tub-removal" },
      { label: "RV and motor home", href: "https://www.flashjunkremoval.com/rv-motor-home-removal" },
      { label: "Dumpster rentals", href: "https://www.flashjunkremoval.com/dumpster-rentals-San-Diego" },
      { label: "Cities", href: "https://www.flashjunkremoval.com/cities-flash-junk-removal" },
      { label: "Contact", href: "https://www.flashjunkremoval.com/contact-flash-junk-removal" },
    ],
  },
  "clear-junk-removal": {
    details: [
      "Clear Junk Removal’s pages cover residential and commercial hauling, furniture disposal, REO cleanouts, property cleanouts, landscaping waste, construction debris, and hot tubs.",
      "They are based in Scripps Ranch and list North County cities plus same-day appointments.",
    ],
    links: [
      { label: "Services", href: "https://www.clearjunkremoval.com/junk-removal-services-in-san-diego-residential-commercial" },
      { label: "Residential hauling", href: "https://www.clearjunkremoval.com/residential-junk-removal-services-in-san-diego-clear-junk-removal" },
      { label: "Furniture disposal", href: "https://www.clearjunkremoval.com/furniture-disposal" },
      { label: "REO cleanouts", href: "https://www.clearjunkremoval.com/reo-cleanouts-in-san-diego-clear-junk-removal" },
      { label: "Property cleanout", href: "https://www.clearjunkremoval.com/property-cleanout-services-in-san-diego-clear-junk-removal" },
      { label: "Construction debris", href: "https://www.clearjunkremoval.com/construction-debris-disposal" },
      { label: "Landscape waste", href: "https://www.clearjunkremoval.com/landscape-waste-disposal-in-san-diego-clear-junk-removal" },
      { label: "Hot tub or spa disposal", href: "https://www.clearjunkremoval.com/hot-tub-or-spa-disposal" },
    ],
  },
  "junk-rushed": {
    details: [
      "Junk Rushed lists services, areas served, FAQs, about, and contact as separate pages. There are no item-by-item service URLs beyond the services page.",
      "The homepage describes same-day hauling for homes, businesses, and job sites, including yard waste, appliances, and furniture.",
    ],
    links: [
      { label: "Services", href: "https://junkrushed.com/services/" },
      { label: "Areas served", href: "https://junkrushed.com/areas-served/" },
      { label: "FAQs", href: "https://junkrushed.com/faqs/" },
      { label: "About", href: "https://junkrushed.com/about/" },
      { label: "Contact", href: "https://junkrushed.com/contact/" },
    ],
  },
  "pacific-rim-junk": {
    details: [
      "Pacific Rim publishes its own pages for furniture, appliances, e-waste, yard waste, construction debris, and cleanouts.",
      "The company is based in Encinitas and says it covers San Diego County, including same-day pickup.",
    ],
    links: [
      { label: "Furniture removal", href: "https://pacificrimjunk.com/furniture-removal-service/" },
      { label: "Appliance removal", href: "https://pacificrimjunk.com/appliance-removal-service/" },
      { label: "E-waste", href: "https://pacificrimjunk.com/e-waste-removal-services/" },
      { label: "Yard waste", href: "https://pacificrimjunk.com/yard-waste-removal-service/" },
      { label: "Construction debris", href: "https://pacificrimjunk.com/construction-debris-removal-service/" },
      { label: "Cleanouts", href: "https://pacificrimjunk.com/clean-out-services/" },
      { label: "About", href: "https://pacificrimjunk.com/about-pacific/" },
    ],
  },
  "strong-hauling": {
    details: [
      "Strong Hauling is a one-page site for the whole county, open daily 7 AM to 7 PM, and the page says there is no extra charge after hours.",
      "The services list on that page includes furniture, mattresses, couches, garage cleanup, hoarder cleanouts, hot tubs and spas, appliances, TVs, exercise equipment, scrap metal, sheds, fences, yard waste, and dirt and concrete.",
      "They name cities from Chula Vista and National City through North County, East County, and beach towns. There are no separate service URLs.",
    ],
    links: [],
  },
  "the-junkiez": {
    details: [
      "The Junkiez San Diego site is a single page. It describes same-day pickup for furniture, appliances, and cleanouts, and also names Orange County and Los Angeles.",
      "The San Diego number on the page is (619) 759-7005. There are no separate service URLs to link.",
    ],
    links: [],
  },
  "monarch-junk-removal": {
    details: [
      "Monarch has services, furniture, commercial, service-area, and pricing pages, plus online booking.",
      "The site says the company is veteran-owned, covers San Diego County, and takes furniture, appliances, yard waste, office junk, and hot tubs.",
    ],
    links: [
      { label: "Services", href: "https://monarchjunkremoval.com/services/" },
      { label: "Furniture", href: "https://monarchjunkremoval.com/furniture/" },
      { label: "Commercial", href: "https://monarchjunkremoval.com/commercial-junk-removal/" },
      { label: "Junk hauling", href: "https://monarchjunkremoval.com/junk-hauling/" },
      { label: "Service area", href: "https://monarchjunkremoval.com/service-area/" },
      { label: "Pricing", href: "https://monarchjunkremoval.com/pricing/" },
      { label: "Book now", href: "https://monarchjunkremoval.com/contact/" },
    ],
  },
  "fetch-junk": {
    details: [
      "FETCH publishes appliance removal, mattress removal, and a junk-removal pricing page, plus city pages for La Mesa, El Cajon, and Santee.",
      "They also offer online booking. The La Mesa crew says quotes can be given from texted photos and that hours run early to late, seven days.",
    ],
    links: [
      { label: "Services", href: "https://www.fetchjunk.com/services/" },
      { label: "Appliance removal", href: "https://www.fetchjunk.com/appliance-removal/" },
      { label: "Mattress removal", href: "https://www.fetchjunk.com/mattress-removal/" },
      { label: "Pricing", href: "https://www.fetchjunk.com/junk-removal-pricing/" },
      { label: "La Mesa", href: "https://www.fetchjunk.com/junk-removal-la-mesa/" },
      { label: "El Cajon", href: "https://www.fetchjunk.com/junk-removal-el-cajon/" },
      { label: "Book now", href: "https://www.fetchjunk.com/book-now/" },
      { label: "About", href: "https://www.fetchjunk.com/about/" },
    ],
  },
  "you-call-it-we-haul-it": {
    details: [
      "You Call It We Haul It lists appliance, furniture, residential, and commercial removal, plus construction debris, yard waste, jacuzzi removal, demolition, and truck rentals.",
      "The Chula Vista company publishes a long city list and a service-area page, and says same-day or next-day service is available.",
    ],
    links: [
      { label: "Waste removal", href: "https://www.youcallitwehaulitca.com/waste-removal-services" },
      { label: "Furniture removal", href: "https://www.youcallitwehaulitca.com/furniture-removal" },
      { label: "Appliance removal", href: "https://www.youcallitwehaulitca.com/appliance-removal" },
      { label: "Jacuzzi removal", href: "https://www.youcallitwehaulitca.com/jacuzzi-removal" },
      { label: "Residential", href: "https://www.youcallitwehaulitca.com/residential-junk-removal" },
      { label: "Commercial", href: "https://www.youcallitwehaulitca.com/commercial-junk-removal" },
      { label: "Construction and yard waste", href: "https://www.youcallitwehaulitca.com/construction-debris-and-yard-waste" },
      { label: "Demolition", href: "https://www.youcallitwehaulitca.com/demolition-services" },
      { label: "Service area", href: "https://www.youcallitwehaulitca.com/service-area" },
      { label: "FAQs", href: "https://www.youcallitwehaulitca.com/faqs" },
    ],
  },
  "junk-haul-team": {
    details: [
      "Junk Haul Team has pages for furniture, appliances, construction cleanup, yard debris, property cleanouts, and storage units.",
      "The site describes a veteran-owned San Diego crew with same-day service.",
    ],
    links: [
      { label: "Furniture removal", href: "https://junkhaulteam.com/furniture-removal-san-diego/" },
      { label: "Appliance removal", href: "https://junkhaulteam.com/appliance-removal-san-diego/" },
      { label: "Construction cleanup", href: "https://junkhaulteam.com/construction-cleanup-san-diego/" },
      { label: "Yard and debris", href: "https://junkhaulteam.com/yard-debris-removal-san-diego/" },
      { label: "Property cleanout", href: "https://junkhaulteam.com/property-clean-out-san-diego/" },
      { label: "Storage unit cleanout", href: "https://junkhaulteam.com/storage-unit-clean-out-san-diego/" },
      { label: "About", href: "https://junkhaulteam.com/about-us/" },
    ],
  },
};
